### PR TITLE
Allow 8 Wiimotes

### PR DESCRIPTION
**Pull request by qwertychouskie**
Since STK now allows 8 players locally.

### CODE REVIEW

**Comment by Alayan-stk-2** [comment]
@qwertychouskie I assume you've tested going over 4 and it didn't create issues ?

**Comment by gitspooky** [comment]
@drvgxnkxng

**Comment by Alayan-stk-2** [comment]
@qwertychouskie So did you test it ?

**Comment by qwertychouskie** [comment]
@Alayan-stk-2 I keep forgetting to test when I'm at my friend's house, and I only own 4 Wiimotes personally.  Feel free to keep pinging me ;)

**Comment by BO41** [comment]
> Feel free to keep pinging me

Ping :)

**Pull request closed without merging**
