### PR TITLE
Add memory total for NVIDIA cards in the logs

### PR DESCRIPTION
**Pull request by devnexen**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
maybe better to ```#define GL_GPU_MEM_INFO_TOTAL_AVAILABLE_MEM_NVX 0x9048``` first

**Comment by devnexen** [comment]
sure

**Comment by Benau** [comment]
hmm not sure if need ifndef xxx define xxx to prevent duplicated #define.......

**Comment by Benau** [comment]
tgs9

**Pull request merged**
