### PR TITLE
irrlicht custom allocator warning build fix proposal.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Benau** [comment]
Now clang warns about unknown pragma...
maybe it can be done without pragma, otherwise just ignore it.....

**Comment by devnexen** [comment]
was wrong only gcc complains originally

**Comment by Benau** [comment]
Now it becomes uglier..... you sure there is no other solution without pragma?

**Comment by Benau** [comment]
Or maybe gcc needs patching

**Comment by devnexen** [comment]
> Or maybe gcc needs patching

let's say today compiler become slightly oversensitive over things :)

anyway it s just a small change this file won t be changed anytime soon (unless you use also the fast allocator but I do not think you would).

**Comment by qwertychouskie** [comment]
IMHO this should be merged, right now building STK is very build-warning-spammy, making it harder to notice legit issues.

**Comment by Benau** [comment]
I would suggest just use clang instead because other than this warning there are so much more false positive warning produced by gcc

**Pull request closed without merging**
