### PR TITLE
A better solution for those scaling issues in high or creepy resolutions 

### PR DESCRIPTION
**Pull request by dumaosen**
They are my fixes of the scaling issues appear in the game.
Here are some pictures:
stk1
stk2
stk3
stk4
stk5
stk6
stk7
stk8
stk9
And more!

### CODE REVIEW

**Comment by Alayan-stk-2** [comment]
I only have a 1920x1080 screen so I can't really test the changes at big resolutions.

I had a quick look at the code and spotted nothing clearly wrong, though.

**Comment by dumaosen** [comment]
**WARNING: CRAZY PART**

**Comment by Alayan-stk-2** [comment]
@dumaosen Is it ready or do you plan and adding even more changes to this PR ?

**Comment by dumaosen** [comment]
> @dumaosen Is it ready or do you plan and adding even more changes to this PR ?

Actually MORE

**Comment by dumaosen** [comment]
My commits are mess up
Close it and open a new one

**Comment by Alayan-stk-2** [comment]
@dumaosen Do NOT use 50 different commits with all a single one-liner change. If you want to do the same kind of simple change in many files, put that together in one commit (change the files, git -add them, then do a git commit which will be for all these changes).

Example : https://github.com/supertuxkart/stk-code/commit/df087d44c49466f3a85dd2c991e92d23663ce573#diff-702a90eeef10979f33118fcc922e5e1a

As Benau told you, this create email spam.

But this is also bad for the commit's history.

When a PR makes many changes, it's better to have a few different commits in it than having to squash&merge all it a single one. With a few different separate commits with logically grouped changes, it's easier to look up one specific code change, to understand it and to eventually track a bug if one is introduced.

But having tons of trivial commits is a terrible clutter and I'd rather do a squash&merge than having tons of trivial commits in the trunk.

**Pull request closed without merging**
