### PR TITLE
Debug input refactoring

### PR DESCRIPTION
**Pull request by luffah**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
Hello, as indicated in input_manager.cpp , debug actions had to be moved in debug.cpp.
Here my proposal of refactoring:
- key with no associated action are parsed by Debug::handleStaticAction
- given they are already computed : the key, its value and modifiers, and current world are forwarded to the Debug method 
- in order to make the static shortcut more understandable, they are all in the same file (new file keyboard_static_keys.hpp)
- added a lock in debug.cpp to avoid multiple events on 1 key stroke

### CODE REVIEW

**Comment by luffah** [comment]
Note : If the numbers of commit is a problem (due to the merge). I'll redo a new one from last version.

**Comment by Benau** [comment]
```
#ifndef HEADER_KEYBOARD_STATIC_KEYS_HPP
#define HEADER_KEYBOARD_STATIC_KEYS_CONFIG_HPP
```

**Comment by luffah** [comment]
(done)

**Comment by luffah** [comment]
Shall this PR be closed (and converted to a future release issue) or be reworked as soon as possible ?

**Comment by Benau** [comment]
...because it looks more complicated after refactoring

**Comment by luffah** [comment]
Not convinced by the argument, cause there is less code repeat. The code referencing semantic instead of the concrete key. is easier to read IMHO.
But indeed, there is many lines in that change on a point that is only about debug mode.

Ok. let's forget this.

**Pull request closed without merging**
