### PR TITLE
Few improvements of spinner and option UI

### PR DESCRIPTION
**Pull request by risostk**
Hi, the changes are:
1. When a spinner is not active, still show its value instead of showing "-".
2. Show the camera name in custom_camera_setting UI
3. On the audio setting UI, disable the spinner if the checkbox is not ticked.

Here are some screenshots. Hope you like it.

Screenshot from 2020-12-24 14-24-56
Screenshot from 2020-12-24 14-25-11
Screenshot from 2020-12-24 15-32-20

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
the "When a spinner is not active, still show its value instead of showing "-"." may break some screen....

**Comment by risostk** [comment]
> the "When a spinner is not active, still show its value instead of showing "-"." may break some screen....

Hi, I was aware of that. I manually checked all the spinners and didn't see any weird behavior. Here is a summary:

kart_color_slider: 
- toggle-slider: (manual check) correct behavior

server_configuration_dialog: 
- more-options-spinner: no setActive is used

splitscreen_player_dialog:
- name-spinner: no setActive is used

addons_screen:
- filter_date: no setActive is used
- filter_rating: no setActive is used

edit_track:
- laps: no setActive is used

gp_info_screen:
- ai-spinner: only setActive(true)
- reverse-spinner: no setActive is used
- track-spinner: no setActive is used
- group-spinner: no setActive is used

options_ui:
- skinchoice: (manual check) correct behavior
- minimap: no setActive is used
- splitscreen_method: (manual check) correct behavior
- font_size (gauge): (manual check) correct behavior
- camera_present: no setActive is used

options_video:
- vsync: (manual check) correct behavior
- blur_level (gauge): (manual check) correct behavior

track_info_screen:
- target-type-spinner: (manual check) correct behavior
- target-value-spinner: (manual check) correct behavior
- ai-spinner: (manual check) correct behavior
- ai-blue-spinner: (manual check) correct behavior

tracks:
- lap-spinner: no setActive is used

create_server:
- more-options-spiner: no setActive is used

**Comment by risostk** [comment]
btw, on kart_color_slider screen, in toggleSlider() function, why use setValue(100) instead of using setValue(getDefaultKartColor())?

**Comment by Benau** [comment]
maybe that was a mistake

**Comment by Benau** [comment]
and online multiplayer split screen kart selection?

**Comment by risostk** [comment]
> and online multiplayer split screen kart selection?

You mean this one? I didn't see weird behavior.
Screenshot from 2020-12-25 13-21-47

**Comment by Benau** [comment]
ok

**Pull request merged**
