### PR TITLE
RESIZE EVERYTHING

### PR DESCRIPTION
**Pull request by CodingJellyfish**
Known issues:
~~Some specfic widgets disappears when going into the screen 2nd time.~~
~~Unknown image appears on the top left corner when resizing kart selection.~~
Dynamic ribbon can go over dialogs.
~~Text box in user screen is broken at the first time going into the screen.~~
~~Loading screen cannot resize properly.~~
~~Text cannot break properly in network lobby~~
~~Ghost screen header could disappear~~

### CODE REVIEW

**Comment by pjlafren** [comment]
I was working on resizing ModalDialogs just last week. After skimming this, you've definitely got a better implementation than me.

I'll test this out and give you a review when I find the time. Can't now 'cause I'm playing ranked ;-)

**Comment by pjlafren** [comment]
Quick testing feedback v1: 

Resizing while a dialog is open in the option menu (custom graphics settings & add a new input device) yields broken graphics. Either the buttons are in the wrong place, or the underlying screen has elements shown above the dialog.

Resizing while in a loading screen looks broken. I don't know if it's worth fixing this one.

Resizing is blocked while in the options menu in game. I.e. start a race, then select the options menu from the pause menu. Not only is resizing blocked there, but the game stops being resizable until you return to the main menu. This does not happen for the help screen while in a race. I have a patch, but github apparently doesn't support uploading patches? I'm not used to github, so I'll find a way.

Also, and this is my kernel dev speaking, it would be nice if you had commit messages. That doesn't seem to be customary for this project, so I guess I'll just have to deal with it.

**Comment by CodingJellyfish** [comment]
> Quick testing feedback v1:
> 
> Resizing while a dialog is open in the option menu (custom graphics settings & add a new input device) yields broken graphics. Either the buttons are in the wrong place, or the underlying screen has elements shown above the dialog.
> 
> Resizing while in a loading screen looks broken. I don't know if it's worth fixing this one.
> 
> Resizing is blocked while in the options menu in game. I.e. start a race, then select the options menu from the pause menu. Not only is resizing blocked there, but the game stops being resizable until you return to the main menu. This does not happen for the help screen while in a race. The fix is simple: [0001-Allow-resizing-the-options-menu-while-in-game.patch.txt](https://github.com/supertuxkart/stk-code/files/13328702/0001-Allow-resizing-the-options-menu-while-in-game.patch.txt)
> 
> Also, and this is my kernel dev speaking, it would be nice if you had commit messages. That doesn't seem to be customary for this project, so I guess I'll just have to deal with it.

For the third bug the old code of disabling windows resizable is not completely deleted yet. And it's better if you have video of the other bugs.

**Comment by pjlafren** [comment]
Loading after resize:
resized_loading

Graphics menu w/ dialog before & after:

graphics_option_before
graphics_option_after

Input menu w/ dialog before & after:

input_option_before
input_option_after

Are those pictures good?

**Comment by CodingJellyfish** [comment]
Loading screen bug not reproducible. Highly because it's a lag between screen resizing.

**Comment by Benau** [comment]
photo_2024-04-19_18-19-37
photo_2024-04-19_18-19-44

**Pull request closed without merging**
