### PR TITLE
stk-code: Rework Windows installer to build directly from source tree

### PR DESCRIPTION
**Pull request by MattDevo**

### CODE REVIEW

**Comment by MattDevo** [comment]
added a slightly more paranoid sanity check on the installation dir per leyyin's guidance

**Comment by deveee** [comment]
Note that in case of removing OpenAL installer, we need also update dependencies for Visual Studio. Current openal32.dll library from our dependencies, depends on msvcr90.dll library (which we don't want at all).

Newest OpenAL needs two files to make it working: openal32.dll and wrap_oal.dll.

More info in this ticket:
https://github.com/supertuxkart/stk-code/issues/2330

**Comment by MattDevo** [comment]
@deveee I agree, the non-mingw Windows dependencies need to be updated as well.  I'm happy to modify the Windows build stuff to use the dependencies repo instead of a packaged distribution if that's the preferred method going forward

**Comment by Benau** [comment]
Hmm, so what's the idea for this PR, which is for 0.9.1?

**Comment by qwertychouskie** [comment]
What is the status of this?  I know we had some Installer work since this PR was made, is this still of any use?

**Pull request closed without merging**
