### PR TITLE
See grand prix high scores in the GUI high score manager

### PR DESCRIPTION
**Pull request by RQWorldblender**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
Allows viewing and removing Grand Prix high score entries from within the GUI. Starting Grand Prix modes are currently disabled, as there is no way to replay it with the previously used minor mode, and which tracks are set to be driven in reverse. A response to #4566, where Grand Prix high scores can be added, but can't be removed in-game.

An additional GUI data file that I have forgotten to remove months ago has been removed here. I'm sure that it's not used anywhere in the current code.

### CODE REVIEW

**Comment by Benau** [comment]
```c++
if (m_major_mode == RaceManager::MAJOR_MODE_GRAND_PRIX)
    track_type_name = "Grand Prix";
else
    track_type_name = "Track";
```
no _() for translation

**Comment by Benau** [comment]
If it's too complicated just do less

**Comment by RQWorldblender** [comment]
> If it's too complicated just do less

I was still going to add checks for locked tracks so they can't be started from the high score info dialog before being unlocked. However, for new players they normally don't have entries of high scores from locked tracks. Should I continue with this?

**Comment by Benau** [comment]
you decide

**Comment by RQWorldblender** [comment]
> you decide

I'm going to continue with having locked tracks be unplayable from the high scores info dialog. I don't want people working around the locked statuses by importing high scores from another profile, and it's likely something most AAA games will do. Once I'm done, I need you to reopen this PR so I can have the additional commits merged.

**Comment by RQWorldblender** [comment]
@Benau You can reopen the PR for the one commit I made now. Though additional testing, the game can still crash after removal of an add-on track, which can mess up the list presented.

**Review by WALEEDANAM — COMMENTED** [review]
RQWorldblender:see_grand_prix_high_scores

**Comment by Benau** [comment]
There is no way to reopen a closed PR so I merge your commit myself

maybe the highscore manager should auto remove highscore if track not found

**Pull request merged**
