### PR TITLE
add camera settings in option screen

### PR DESCRIPTION
**Pull request by luffah**
Hello,

~~This PR shall be in draft state ATM.~~

Features :
- include hard coded presets (+ 1 custom) that specify : `fov, camera_forward_distance, camera_forward_up_angle, smoothing, camera_backward_angle`
- camera settings can be changed in game

It adds camera settings (with presets) in ui option screen.

Option screen

[Edited : Rendering without Spectator camera things]

2020-04-24-221707_1360x720_scrot

There will probably be many points to discuss :

- about adding camera parameter in user config `config.xml` (only for 1 player)
- about naming of the presets (currently there is 2 presets : "Standard" , "Drone Chase")
- about adding the settings in the ui part
- about modification of the spinner widget to support float values
- about allowing to change or not the camera position during game

Notes:

-  Fov setting is not used in splitscreen multiplayer mode 
-  The option about use ball camera can be placed ui screen extra options checkbox
-  ~~The options about spectator camera can be put in another screen or in another advanced setting like a live zooming.~~
 

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
you need to ask if alayan want that many options in the screen....

**Comment by luffah** [comment]
I added a [poll](https://luffah.xyz/wiki/supertuxkart/stk_adding_feature) on my unofficial wiki to know users preferences.

**Comment by luffah** [comment]
Rendering with Spectator camera things.

2020-04-24-221707_1360x720_scrot

**Comment by luffah** [comment]
@Alayan-stk it seems difficult to me to put less options to set up camera.

Could be these additional settings acceptable for you ?

**Comment by luffah** [comment]
I undraft this because it is a wanted feature by some notable players.

**Comment by Benau** [comment]
appveyor failed...

**Comment by Benau** [comment]
also if you are going to use UserConfigParams::m_camera_distance directly then you should not rely on kart properties at all

**Comment by zyk660066** [comment]
---原始邮件---
发件人:&quot;Benau&quot;<notifications@github.com&gt;
发送时间:2020年7月5日 星期日 上午9:40
收件人:&quot;supertuxkart/stk-code&quot;<stk-code@noreply.github.com&gt;
抄送:&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;
主题:Re: [supertuxkart/stk-code] add camera settings in option screen (#4273)



also&nbsp;if&nbsp;you&nbsp;are&nbsp;going&nbsp;to&nbsp;use&nbsp;UserConfigParams::m_camera_distance&nbsp;directly&nbsp;then&nbsp;you&nbsp;should&nbsp;not&nbsp;rely&nbsp;on&nbsp;kart&nbsp;properties&nbsp;at&nbsp;all

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;are&nbsp;subscribed&nbsp;to&nbsp;this&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by luffah** [comment]
You mean removing the method `float KartProperties::getCameraDistance() const` in kart properties ?

I don't have absolute answer to that :
  if someone introduce a microscopic or giant kart (or with bonus, like mushroom drugs things in commercial equivalent),
  then camera distance shall have a factor. 

Shall we remove camera settings from kart properties ? or keeping relative values (factor) ?

**Comment by Benau** [comment]
because the way you do that now it will be overwritten by update_kart_properties.py, so yes please remove it

**Comment by luffah** [comment]
The change will apply to all camera properties on kart : distance, backward/forward camera angle, smoothing

**Comment by Benau** [comment]
```
        ModalDialog::dismiss();
        OptionsScreenUI::getInstance()->updateCameraPresetSpinner();
        return GUIEngine::EVENT_BLOCK;
```

```
        m_self_destroy = true;
        return GUIEngine::EVENT_BLOCK;
```
onOpdate() if m_self_destroy ModalDialog::dismiss();

**Comment by luffah** [comment]
I re-used some code from `splitscreen_player_dialog.hpp` to do what you asked.

I kept `OptionsScreenUI::getInstance()->updateCameraPresetSpinner();` because it is required to update the preset name regarding the values.

**Comment by luffah** [comment]
Damn i don't think i can't do anything about this MsBuild error in AppVeyor...

**Comment by Benau** [comment]
not sure @Alayan-stk-2 ok for these configuration

**Comment by Benau** [comment]
lol alayan not sure france will allow hk immigrant

**Comment by luffah** [comment]
(self-censorship...) but yes it will for you

**Pull request merged**
