### PR TITLE
Change "Geometry detail" to "Level of Detail", small tweaks

### PR DESCRIPTION
**Pull request by qwertychouskie**
Changed for clarity as it controls whether extra objects are shown or not.  Also changed a message to make it accurate regarding current behavior.

### CODE REVIEW

**Comment by Benau** [comment]
Please don't change our copyright header, your PR will be reject if you do so

**Comment by MTres19** [comment]
@qwertychouskie Geometry detail level and LOD aren't the same thing. LOD changes the geometry based on distance from the camera; geometry detail level restricts it to a certain level based on the user's config. They're completely different things and we don't want confusion.

**Comment by samuncle** [comment]
Hi, as one of the dev who had the idea of Geometry Detail I specifficaly choose a different name because they are two different concepts:

1) Level of detail = An object that's displayed depending on the distance to the player
2) Geometry detail = An object is load or not depending on the user setting

It avoid confusion when you code and also when you create tracks

**Comment by qwertychouskie** [comment]
When I think of "Geometry detail", I think of how low poly/high poly.  Maybe something like "Scenery level"?

**Comment by MTres19** [comment]
That IS more descriptive.

**Comment by qwertychouskie** [comment]
New commit pushed, should be fixed.

**Comment by auriamg** [comment]
"Level of scenery" is not clear at all, "Geometry detail" seems much clearer to me. In any case this is all buried in advanced options. I don't think this PR is an improvement. Next time, please check with us before creating a pull request that we actually _want_ the terminology changed.

**Pull request closed without merging**
