### PR TITLE
Initial works on tips manager

### PR DESCRIPTION
**Pull request by dumaosen**
tips

## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
### WARNING: big PR
The initial work on tips manager.
Things to do, which should be in different PRs:
A lightbulb icon;
More useful tips and guide of tips.xml;

### CODE REVIEW

**Comment by dumaosen** [comment]
Before the PR is merged, i need a feature: Make it possible to start a screen from a dialog.

**Comment by risostk** [comment]
maosen, I like this feature.

**Comment by Benau** [comment]
actually you may mis-understand what alayan wants in his ticket...

you can just use some scripting to open a dialog (with tips) when challenge failed other then adding thousand line of not so useful and hardcoded code

next time please ask more before implementing some feature

**Comment by dumaosen** [comment]
though the pr isnt merged, i am happy. i successfully jumped out the comfort zone of guiengine through it. if someone likes it, you can merge or even maintain the branch. i will make a simple version later.

**Pull request closed without merging**
