### PR TITLE
Modern skin

### PR DESCRIPTION
**Pull request by qwertychouskie**
The culmination of years worth of work!  Thanks to all who helped make this as amazing as possible!
PNGs were ran through `pngquant` then `optimize_data.sh` for maximum smallness.
`213 items, totalling 1.5 MiB (1,576,115 bytes)`

### CODE REVIEW

**Comment by Benau** [comment]
Not sure @Alayan-stk-2 is isolated because of chinese virus lol.....

**Comment by Benau** [comment]
data/gui/icons/android.png is not used anymore

Maybe it's time to bring back font thickness code to save ttf to make distro happy

**Comment by qwertychouskie** [comment]
@Benau Icons for Android/Windows/Mac/Linux removed, we can add these extra icons to the media repo later.

**Comment by qwertychouskie** [comment]
`5 items, totalling 618.4 KiB (633,272 bytes)`  As for the TTFs, distros will work their magic as they already do with the existing TTFs, and the size is small enough that Android shouldn't be really affected (especially with app bundle support coming).

**Comment by Benau** [comment]
every bytes matter...

**Comment by Benau** [comment]
...Alayan....

**Comment by qwertychouskie** [comment]
@Alayan-stk-2 ^

@Benau Real pings generally work better ;)

**Comment by Benau** [comment]
Alayan most stk fans and even deve think it's a good idea to include this so i will go ahead merge it...

Let hope the chinese virus doesn't affect you too much...

**Comment by deveee** [comment]
Congratulations Qwerty!

**Pull request merged**
