### PR TITLE
New dark skin (coal)

### PR DESCRIPTION
**Pull request by Alayan-stk-2**
This PR adds a new skin to STK.

The colors used are mostly dark grey, with white text.

coalskin1
coalskin2
coalskin3

### CODE REVIEW

**Comment by auriamg** [comment]
@hiker @Arthur-D Any opinions?

**Comment by Alayan-stk-2** [comment]
Video demo showing the theme : https://youtu.be/DzigpKvzUHU

**Comment by auriamg** [comment]
I found a little issue, in splitscreen multiplayer, when selecting kart, the focus color should be the same for the player name spinner and the kart selection focus, but in this screen they are not

**Comment by Alayan-stk-2** [comment]
The ruby skin also suffer from the same issue, although that's less blatant, as it's a pink focus and a deep red spinner.

I'll recolor the spinner so that it matches.

Also, I've been working on a fix for the news text not being readable on the too light bottom bar ; I'll do a separate PR for it soon.

**Pull request merged**
