### PR TITLE
Handle missing libopenglrecorder gracefully

### PR DESCRIPTION
**Pull request by qwertychouskie**

### CODE REVIEW

**Comment by auriamg** [comment]
After discussion, the preferred way to do this would be :

set(PROJECT_VERSION "0.9.1") -> that could say "git", and the default of the recorder could depend on the version (disabled by default for git, enabled by default for release)

**Comment by qwertychouskie** [comment]
The problem is version number is easily forgotten (it was still at 0.9.1!).

**Comment by hiker** [comment]
That 'number' should always be 'git' on any dev branch.

Gee, just went back through the history, looks like it has been not-git ... forever :(
So as part of this, set the version in cmake to 'git' - our code is expecting this

**Comment by qwertychouskie** [comment]
@hiker Requested changes implemented.

**Comment by auriamg** [comment]
That seems good, thanks

**Pull request merged**
