### PR TITLE
Fix compiler warning about shift count being bigger than size of type

### PR DESCRIPTION
**Pull request by tobbi**
/stk-code/src/network/network_string.hpp:170:24: warning: shift count >= width of
      type [-Wshift-count-overflow]

### CODE REVIEW

**Comment by auriamg** [comment]
Hi, this does not seem like an actual fix; while it does suppress the warning, it doesn't actually change the behavior of the code, so if there actually was the issue the warning is telling us about then the original issue is not actually fixed, merely hidden

**Comment by tobbi** [comment]
I was told on IRC that this is the intended behaviour for this code.

**Comment by leyyin** [comment]
Hi, @Flakebi also fixed this issue some time ago in his PR #1907 (commit Flakebi/stk-code@19ce80656330293a).

**Comment by tobbi** [comment]
This has been fixed, presumably by the above pull request.

**Pull request closed without merging**
