### PR TITLE
Adding appveyor config file

### PR DESCRIPTION
**Pull request by nado**
Only x86 VS 2015
No notification, probably best for the first uses.

All you need to do to start using the appveyor CI is to create an account and link the GH repo to it, and select branches or PR to be built.

See #2649 for the rest of the discussion

### CODE REVIEW

**Comment by leyyin** [comment]
Can someone please review this? @hiker @auriamg

**Comment by auriamg** [comment]
Hiker also created an official STK account on appveyor

**Comment by hiker** [comment]
First build successful - great!! 

I wonder if it is possible to get irc notifications?  Also it appears that notifications are sent to the email address set for the account (in this case our official stk email address). Is it possible to send the notifications to the committer  instead?

**Comment by hiker** [comment]
OOops, I should have added this to the ticket #2649, not to the pull request ... doing this now ;)

**Pull request merged**
