### PR TITLE
Branch1

### PR DESCRIPTION
**Pull request by NalinG**
Hi,

I sent the event and caught it in the spinner widget class but I am not sure as to how to check cursor's position as the m_mouse_pos is not accessible in spinner widget class and before doing any major changes I thought I should probably ask for some help.

One thing I can do is use some external function like GetCursorPos().
Another thing was to make m_mouse_pos accessible in our spinner widget class but then I think it will not relate to the same event.

Can someone please guide me any further,

Thank you and sorry if I am asking some stupid or basic doubt.
Please bear with me.

### CODE REVIEW

**Comment by konstin** [comment]
First of all, you should use a new branch when you start to work on something new. Your current pull request still contains the changes for #1850. Then, always merge with upstream before opening a pull request (GitHub displays you if it merges on the pull-request creation page). Finally squash old commit by rebasing: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request.

For getting the event you need, simply look at the `else if (originator == "spinnerbody" || originator == m_properties[PROP_ID])` section in `SpinnerWidget::transmitEvent`. If there is no listener, you should use `GUIEngine::EventHandler::get()->getMousePos()` to get the mouse pos and then check wether the click was inside the expected range and set the value appropriatly. If the click was outside or there is a listener, do nothing.

**Comment by NalinG** [comment]
Thanks a lot @konstin .
And yeah, I will be careful with my PR from next time.

Thanks.

**Comment by auriamg** [comment]
I just want to clarify things a bit. SpinnerWidget::transmitEvent and SpinnerWidget::LeftPressed are probably unrelated to what we want here (depending on the solution that is implemented). I was thinking adding a new callback, totally separate from transmitEvent, which handles raw mouse events

**Comment by NalinG** [comment]
Okay, just to clarify, cannot we just add another virtual function in the widget class for raw mouse clicks and then call it.

If not can you please explain a bit what you want and why the above mentioned method wont work.?

Thank You

**Comment by NalinG** [comment]
Also, should I send a new pull request.

**Comment by auriamg** [comment]
Yes, adding a new virtual method in widget would work well.

As for creating a new pull request, this may be preferable (using a new branch), since this pull request now contains some unrelated stuff

**Comment by NalinG** [comment]
Okay.

**Comment by hiker** [comment]
@auriamg I have no idea what this is supposed to do, it appears outdated. Should this just be closed?

**Comment by Flakebi** [comment]
I think it can be closed now. If I understand it correctly, @ZyperPL did that in #2025.

**Comment by auriamg** [comment]
Closing this pull request as outdated, since it's not been updated in quite a while and also contains unrelated changes mixed together. If you wish to continue working on STK, please open separate pull requests for the different changes. Thanks!

**Pull request closed without merging**
