### PR TITLE
IrrDeviceWayland: Don't try to use non-existent wl_pointer object

### PR DESCRIPTION
**Pull request by dos1**
## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by deveee** [comment]
Merged, thanks.

**Comment by deveee** [comment]
@dos1 so does STK already work on Librem?

**Comment by dos1** [comment]
It needs hidpi support and a fix for Wayland backend to take output scale and rotation into account when processing modes - but otherwise, yeah, it works :)

I'm using this, obviously not mergable yet, patch to play in landscape orientation:

```diff
diff --git a/lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp b/lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
index cbfa0e6..c01ce7c 100644
--- a/lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
+++ b/lib/irrlicht/source/Irrlicht/CIrrDeviceWayland.cpp
@@ -106,8 +106,8 @@ public:
     {
         CIrrDeviceWayland* device = static_cast<CIrrDeviceWayland*>(data);
 
-        device->getCursorControl()->setPosition(wl_fixed_to_int(sx),
-                                                wl_fixed_to_int(sy));
+        device->getCursorControl()->setPosition(wl_fixed_to_int(sx) * 2,
+                                                wl_fixed_to_int(sy) * 2);
 
         SEvent irrevent;
         irrevent.EventType = irr::EET_MOUSE_INPUT_EVENT;
@@ -468,8 +468,8 @@ public:
         event.EventType = EET_TOUCH_INPUT_EVENT;
         event.TouchInput.Event = ETIE_PRESSED_DOWN;
         event.TouchInput.ID = id;
-        event.TouchInput.X = wl_fixed_to_int(x);
-        event.TouchInput.Y = wl_fixed_to_int(y);
+        event.TouchInput.X = wl_fixed_to_int(x) * 2;
+        event.TouchInput.Y = wl_fixed_to_int(y) * 2;
         
         device->signalEvent(event);
              
@@ -515,8 +515,8 @@ public:
         event.EventType = EET_TOUCH_INPUT_EVENT;
         event.TouchInput.Event = ETIE_MOVED;
         event.TouchInput.ID = id;
-        event.TouchInput.X = wl_fixed_to_int(x);
-        event.TouchInput.Y = wl_fixed_to_int(y);
+        event.TouchInput.X = wl_fixed_to_int(x) * 2;
+        event.TouchInput.Y = wl_fixed_to_int(y) * 2;
         
         device->signalEvent(event);
         
@@ -606,12 +606,12 @@ public:
     {
         CIrrDeviceWayland* device = static_cast<CIrrDeviceWayland*>(data);
 
-        device->VideoModeList.addMode(core::dimension2du(width, height), 24);
+        device->VideoModeList.addMode(core::dimension2du(height, width), 24);
 
         if (flags & WL_OUTPUT_MODE_CURRENT)
         {
-            device->VideoModeList.setDesktop(24, core::dimension2du(width,
-                                                                    height));
+            device->VideoModeList.setDesktop(24, core::dimension2du(height,
+                                                                    width));
         }
     }
 
@@ -693,7 +693,7 @@ public:
         if (interface_str == "wl_compositor")
         {
             device->m_compositor = static_cast<wl_compositor*>(wl_registry_bind(
-                                  registry, name, &wl_compositor_interface, 1));
+                                  registry, name, &wl_compositor_interface, 3));
         }
         else if (interface_str == "wl_shell")
         {
@@ -1201,6 +1201,8 @@ bool CIrrDeviceWayland::createWindow()
     wl_surface_set_opaque_region(m_surface, region);
     wl_region_destroy(region);
 
+    wl_surface_set_buffer_scale(m_surface, 2);
+
     if (m_shm)
     {
         m_cursor_surface = wl_compositor_create_surface(m_compositor);
```

**Comment by deveee** [comment]
Good. Feel free to ask if you need some help.

And maybe it's possible to detect that STK runs on Librem and adjust some default parameters, eg. activate touch device by default. like in main_android.cpp.

**Comment by dos1** [comment]
I guess this PR is actually a good hint - touchscreen controls could be automatically enabled when there's touch device, but no pointer object available. This way it would do the right thing on any touch-only Wayland device.

**Pull request merged**
