### PR TITLE
In-game high scores management

### PR DESCRIPTION
**Pull request by RQWorldblender**
Add in-game high score selection screens. The main screen can be accessed from the main menu via a crown icon. They let players have a central place to view and manage their high scores. A race can be started from them, and entries can also be deleted (it deletes the whole top five list). There is also a button at the top-right (the bomb icon) that can clear all high scores. 

Other fixes included:
- The string for the high scores title in the track info screen can now be translated
- Replace bomb icon (as used in the help menu) with the full object version from STK 0.8; most of the transparency has been removed in the object itself
- Fix a minor issue for the comment with difficulty not showing SuperTux difficulty in the config file
- Non-parent armature bone detection is no longer fatal; fix missing space in error

Screenshots (contents may have changed since they were taken):
Screenshot_20210207_141936
Screenshot_20210207_141922
Screenshot_20210207_142125

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
please don't mix non-related stuff in the same PR.....

oh by the way log::error of spm armature will lead to crashing later anyway, so it's better discard the armature in the exporter itself

**Comment by RQWorldblender** [comment]
> please don't mix non-related stuff in the same PR.....
> 
> oh by the way log::error of spm armature will lead to crashing later anyway, so it's better discard the armature in the exporter itself

I just took out the commit that does this change.

**Comment by RQWorldblender** [comment]
> please don't mix non-related stuff in the same PR.....
> 
> oh by the way log::error of spm armature will lead to crashing later anyway, so it's better discard the armature in the exporter itself

Actually, I made a new commit that only fixes the missing space for that part.

**Comment by Benau** [comment]
there are still many unrelated commits..... (custom video settings, tutorial......)

**Comment by RQWorldblender** [comment]
> there are still many unrelated commits..... (custom video settings, tutorial......)

I got rid of some more of these commits now. I might put these into separate PRs soon.

**Comment by Benau** [comment]
no sources.cmake change...

**Comment by RQWorldblender** [comment]
> no sources.cmake change...

Fixed that now.

**Comment by Benau** [comment]
```
    else if(ModalDialog::isADialogActive())
    {
        if(ModalDialog::getCurrent()->onEscapePressed())
            ModalDialog::getCurrent()->dismiss();
    }
```
richard state_manager will run dismiss for you so you don't need a custom onEscapePressed handling in your dialog

**Comment by RQWorldblender** [comment]
> richard state_manager will run dismiss for you so you don't need a custom onEscapePressed handling in your dialog 

I took care of that now. While doing this, I'll also have these done:
- Do not write high scores if a race has 0 karts or 0 laps
- Allow disabling high scores writing temporarily with a command line switch

**Comment by Benau** [comment]
it crashes because m_back_widget is not initialized in your dialog at all..........

**Comment by RQWorldblender** [comment]
That has been taken care of, but I have not yet pushed the changes.

**Comment by Benau** [comment]
good

**Comment by RQWorldblender** [comment]
I got the changes pushed now. There are some more minor ones that relate to high scores, but deal with when they are written.

**Pull request merged**
