### PR TITLE
Super Speedometer

### PR DESCRIPTION
**Pull request by CodingJellyfish**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
An improvement of #4099 
It adds total kart & speed evaluation 
Todos:
Make rank somewhere else possible

### CODE REVIEW

**Comment by luffah** [comment]
@dumaosen  Nice job. But it still can be better. If i can comment
- for rank display the rendering of the digits looks poor.
- for speed view, it shall be smoothed (rounding speed value and maybe limit update to 4 time per second max) 
- i don't to choose between speed and rank...

**Comment by Fouks0** [comment]
I don't think that it needs an update frequency limit but else I agree with everything
We could maybe move the rank near the lap counts, with the "Podium" logo...
Also if we use km/h (which is appropriate), the speedometer picture might have to be changed to have the marks matching km/h and not m/s...

**Comment by Benau** [comment]
outdated.........

**Comment by CodingJellyfish** [comment]
hmm so should I revamp this or just throw it? I’ve found that Benau doesn’t like adding a speedometer option…

**Pull request closed without merging**
