### PR TITLE
Add digital speedometer and units option

### PR DESCRIPTION
**Pull request by RQWorldblender**
Restores and revamps the digital speedometer last seen in STK 0.8.1. It is placed above the current speedometer; its original place is taken by rank number. It can be toggled to show metric and/or imperial units, or be disabled entirely. The latter is the default behavior in new config files, preserving the current behavior while keeping the digital speedometer an option for those who want it. There are now vertical lines that clearly separate each unit to make them easier to discern. Additional options will be written to existing config files, with the default value of None. This unit option is currently not used anywhere else. an additional tip is added to remind users of this new feature.
Options:
- None (default)
- Metric
- Imperial
- Both (Metric on top)
- Both (Imperial on top)
    
Also fix a minor issue for the comment with difficulty not showing SuperTux mode in the config.xml file.

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
I hate options everywhere.....

also i don't even think we want to bring back numeric speedmeter

**Comment by RQWorldblender** [comment]
This is one another one of those things that I was out of the loop on:
Why did the digital speedometer get removed between the 0.8.1 to 0.9.0 transition?

**Comment by Benau** [comment]
lots of thing got removed in 0.9 too like the hit message

**Comment by Benau** [comment]
maybe they are troublesome to be kept

**Comment by Benau** [comment]
i personally don't mind numeric speedometer, just remove all those tips / option... and keep 1 format (km/h) to the code simple

but you need to see if alayan mind

**Comment by Benau** [comment]
actually only fouks speedrunner mod speedometer is acceptable


this no good to be used everywhere......

**Pull request closed without merging**
