### PR TITLE
Update Angelscript from 2.32.0 to 2.35.1

### PR DESCRIPTION
**Pull request by BryanQuigley**
Didn't require any changes from tarball except dos2unix.

Checked and M1 Mac and DragonFly made it upstream.

Not sure how below agreement pertains to this.. but it's clearly not my code. 

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
We made some custom changes in cmakelist to allow building aarch64 in windows.........

And the github actions failling atm, this prevent from being merged...........

**Comment by BryanQuigley** [comment]
Oops, I forgot a new file, that appears to be why it's failing. Will look into  aarch64 in windows

**Comment by Benau** [comment]
```
  Cannot find source file:
172

173
    ../../source/as_callfunc_arm64.cpp
```

**Comment by Benau** [comment]
maybe you can try something like if compiler name == clang define AS_MAX_PORTABILITY for aarch64...

**Comment by BryanQuigley** [comment]
I just tested - and I can move this to just testing in my own fork so I don't keep making noise.

(I also setup a Linux aarch build.. but that works fine :/)

**Comment by Benau** [comment]
if we have  ADD_DEFINITIONS(-DAS_MAX_PORTABILITY)

then

     if(CMAKE_ASM_COMPILER_WORKS)
         set(ANGELSCRIPT_SOURCE ${ANGELSCRIPT_SOURCE} ../../source/as_callfunc_arm64.cpp ../../source/as_callfunc_arm64_gcc.S)
         set_property(SOURCE ../../source/as_callfunc_arm64_gcc.S APPEND PROPERTY COMPILE_FLAGS)
     else()
         message(FATAL ERROR "ARM target requires a working assembler")
     endif()

can be avoided?

**Comment by Benau** [comment]
Let me test in android later..

**Pull request merged**
