### PR TITLE
add a camera mode to spectate soccer in large view that follows the ball

### PR DESCRIPTION
**Pull request by luffah**
This PR, add a camera mode to spectate soccer in large isometric view  that follow the ball (switchable with accel/brake keys).

Related to issue: https://github.com/supertuxkart/stk-code/issues/4238 (no need to check the issue, it is just a technical question with some thougths about UI — a mirror like in _crazyracing kartrider_ —).

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
you should check if dynamic cast fail, also if(x){ should be next line

**Comment by Benau** [comment]
not sure deve wanna add android support or bike do that... 

let hope deve is not isolated because of 🇨🇳 virus....

**Comment by Benau** [comment]
..still if(x) { ....

we use if (x)
{

in stk

**Comment by luffah** [comment]
_China virus ? are you speaking about Tai Chi ?_
Sorry, i'm used to code formatting tools with Python.

**Comment by Benau** [comment]
...if you don't mind can u use 4 spaces for indentation? (there are 2 spaces now for soccer world)

**Comment by luffah** [comment]
.vimrc updated

**Comment by Benau** [comment]
if you don't know the android one then probably let's merge first lol

**Comment by Benau** [comment]
btw why it's if (action == PA_ACCEL || action == PA_BRAKE)?

you only need brake input?

**Comment by luffah** [comment]
Similarly to left/right to change kart, i was thinking about up/down to change camera modes (to possibly add more than 2).

**Comment by Benau** [comment]
then maybe you should change the translation or remove the PA_ACCEL after it's added

**Comment by luffah** [comment]
I prefer first solution… but it gives an ugly message.

**Comment by Benau** [comment]
maybe just use accel button for now?

**Comment by Benau** [comment]
actually if you have just a few camera mode then you switch with only 1 key is quick anyway (and they don't even exist yet)

**Comment by luffah** [comment]
ok only up button for now

**Comment by Benau** [comment]
maybe better english will be
```
Press <%s> or <%s> to change the targeted player, <%s> or <%s> for the camera position.
```

Or alayan / andet!

**Comment by Benau** [comment]
sorry for confusion... 

but "Press <%s> or <%s> to change the targeted player " ", <%s> ..." there will be an extra " " before comma.

**Comment by qwertychouskie** [comment]
@Benau are you saying there should be a space before the comma?  In English there shouldn't be a space before commas, just after them. <- Example

**Comment by Benau** [comment]
...there will be an extra " " before comma which is not good lol

**Comment by luffah** [comment]
Whoaaa faster PR (reviews included) i never seen.

**Pull request merged**
