### PR TITLE
Fix for #3444

### PR DESCRIPTION
**Pull request by 123survesh**
* Added a check for the keyboard input device and changed the text of the "title" widget using **Widget->setText("id")** method
* Have hard coded the string **"Press any key..."** in **src/states_screens/dialogs/press_a_key_dialog.cpp** 

****
## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
you don't need a03ddd8 as it should be run by data/po/update_pot.sh

**Comment by 123survesh** [comment]
@Benau I accidentally closed the last PR, I did a hard reset to revert the changes. I saw in the translation files that some strings were hard coded in the code, so I just hard coded my string as well and added an entry for that string in the translation files :sweat_smile:

**Comment by Benau** [comment]
no they are all added with data/po/update_pot.sh

**Comment by 123survesh** [comment]
Ah alright :+1:

**Pull request merged**
