### PR TITLE
Implement revving, sound not added yet.

### PR DESCRIPTION
**Pull request by qwertychouskie**
Sound coming next, though this will probably take longer, as it was not even working in the original PR. (https://github.com/supertuxkart/stk-code/pull/35/commits/96271c98fbf47038e8cd04302bb76691beae5e40)

### CODE REVIEW

**Comment by Benau** [comment]
Hey, why do you change "a fun racing game with go-kart" to "A racing game"?

Normally all files in STK use the first one

**Comment by Benau** [comment]
You seem don't quite understand "Also please don't copy code from elsewhere without studying what it's really doing"...

**Comment by qwertychouskie** [comment]
Made it match [supertuxkart.appdata.xml](https://github.com/supertuxkart/stk-code/blob/master/data/supertuxkart.appdata.xml).  If you want I can change it to "a fun go-kart racing game" or "a fun racing game with go-karts".  About the copy-paste: Unfortunately, I don't know any C++ other than what I am learning as I do this, (and I won't have time to fully lean anytime soon :( ), so I am using the copy-paste as a start, then modifying from there, as I find things that need changing.

**Comment by auriamg** [comment]
Code like
```
m_penalty_time += 1.0f;
```
cannot be included in STK, this is not framerate-independent

**Comment by auriamg** [comment]
Closing since the code was reviewed as being invalid and was not fixed

**Pull request closed without merging**
