### PR TITLE
add radar / optionnal in user config

### PR DESCRIPTION
**Pull request by luffah**
(this change is an evolution of https://github.com/supertuxkart/stk-code/pull/4210)

Hello,

  This change add a 3D radar (a kind of 2D protactor that follows the kart) that:
  - shows discretly the speed and steering by showing the point reached in 3 ticks
  - if you got a cake item with a target reachable, a square is drawn on the target
  - broadly indicate were to go in arena modes (where is the flag or the base if you already have the flag; where is the ball in soccer mode; where is the nearest opponent in battle mode).
  - points karts that can be a threat (when another player kart is too close to yours, or to the ball) 
  - In soccer mode, it shows where is the ball and how it move and the karts that are around the ball (with gradients to represents the distance).
       - a green vector shows the trajectory of the ball
       - if the ball is reachable, a square is drawn on the ball

  The feature still experimental.
  To use it, edit user config.xml file :
```xml
     <!-- Radar settings
             enable : Enable radar (show target in ctf and soccer modes)
             offset : Radar offset above a the kart
             size : Radar size (default: 1.0) -->
    <radar_display
        enable="true"
        offset="0.200000"
        size="1.000000"
    >
    </radar_display>



```
# Screenshot

Capture d’écran_2020-02-21_00-27-12

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by luffah** [comment]
Note : default values show a smaller radar (globally the size of an astronaut helmet) that does hide nothing.

```
    <radar_display
        enable="true"
        offset="0.25"
        size="0.5"
    >
    </radar_display>
```

**Comment by risostk** [comment]
Radar is a cool idea, I like it.

**Comment by Benau** [comment]
not sure alayan has time to try it...

**Comment by risostk** [comment]
hi, stk seems to overwrite config.xml without the radar display setting.

**Comment by luffah** [comment]
stk overwrite config.xml, but I don't have the problem if activate it after getting the commit and compiling (running stk with the right version).

**Comment by luffah** [comment]
This PR need enhancement :
- adapt radar position to camera position or draw a 2d radar instead
- the 3d curve that represents steering does represent well the kart drifting path

**Comment by risostk** [comment]
Thanks. Guess I put the radar_display in the wrong place. Now it works. Very cool!

**Comment by Benau** [comment]
honestly your code make stk look like a game for cheaters......

you can see if alayan like your code and recreate a new pr (so it doesn't keep generating email when merging master)

**Comment by luffah** [comment]
sorry i thought i had already closed this PR. I agree and will make a request when it will be cleaner.

**Pull request closed without merging**
