### PR TITLE
Update deps from INSTALL.md

### PR DESCRIPTION
**Pull request by qwertychouskie**
(and put them in alphabetical order.)

### CODE REVIEW

**Comment by hiker** [comment]
Sorting them makes sense, but it seems that some dependencies were removed, and others added.
@deveee , any comments?

**Comment by Benau** [comment]
Maybe he wanna update it because he thinks it's the cause of his failure PPA?

But this travis file is for internal buildbot!

**Comment by qwertychouskie** [comment]
It's not about the PPA, I just noticed the deps were out of date (still has `libglu1-mesa-dev`, doesn't have `libfreetype6-dev`, [@devee said libcurl4-gnutls-dev is better](https://github.com/supertuxkart/stk-code/pull/2494#issuecomment-218850006) (2nd paragraph form bottom), etc...)  For more info on the updated list, see https://github.com/supertuxkart/stk-code/pull/2494 and https://github.com/supertuxkart/stk-code/commit/c9f2de81557bccd4c9684503682938347c10cfda.

**Comment by deveee** [comment]
It's just our system that checks compilation errors. As long as it works any modifications have IMO very minor priority. But indeed the dependencies list is now more complete.

**Pull request merged**
