### PR TITLE
[DRAFT] Use relative path for MacOS workflow

### PR DESCRIPTION
**Pull request by tobbi**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

I do not know if this fixes the MacOS builds. Seems too simple a fix.

### CODE REVIEW

**Comment by tobbi** [comment]
Just wanted to mention that the builds started failing when the github runner image was updated:

works:
```
 Image: macos-14-arm64
  Version: 20240625.2
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240625.2/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240625.2
```

Fails:
```
   Image: macos-14-arm64
  Version: 20240701.9
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240701.9/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240701.9
```

**Comment by CodingJellyfish** [comment]
I'm so sorry, it looks like they don't run dylibbundler when it's not merged, so I wrongly merged it

**Comment by tobbi** [comment]
Unfortunately, that didn't fix the issue.

**Comment by tobbi** [comment]
I opened https://github.com/actions/runner-images/issues/10184 for the issue. I'm assuming it's a combination between the dylibbundler and XCode 1.5.0 that's the culprit here.

**Pull request merged**
