### PR TITLE
Using xml.dom.minidom.parse is known to be vulnerable to XML attacks.

### PR DESCRIPTION
**Pull request by ghostslayer989**
changed xml to defusedxml

### CODE REVIEW

**Comment by Alayan-stk-2** [comment]
@ghostslayer989 This code is only used when we want to update the strings for translation. Not only is this never run by end users, it is not run against some external untrusted data, but against the data files that come along with the code and are just as trusted.

Any reason to nonetheless bother with this change ?

**Comment by qwertychouskie** [comment]
I don't see any reason to not merge it...  (People copy code from weird places sometimes, if someone copies the code it should be secure code.)

**Comment by Edm571** [comment]
@ghostslayer989 You have just been invited to creation club! Go to https://creation-club.github.io-org to get started.

**Comment by ghostslayer989** [comment]
> @ghostslayer989 You have just been invited to creation club! Go to [creation-club.github.io-org](https://creation-club.github.io-org) to get started.

???

**Comment by hamidnegahbanaghdami** [comment]
Hi

**Pull request merged**
