### PR TITLE
Allow runtime render switching

### PR DESCRIPTION
**Pull request by qwertychouskie**
Re-base and improvement of https://github.com/supertuxkart/stk-code/pull/4294 after merging of GLAD

I tested both GL and GLES builds and everything rendered properly as far as I could see.  The renderer can be selected by setting the `SUPERTUXKART_RENDERER` env var, e.g. `SUPERTUXKART_RENDERER=GLES supertuxkart`

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
......qwerty i told you i will  vulkan renderer soon and stk modern renderer will no longer use opegl (es)

**Comment by abchk1234** [comment]
The OpenGL(ES) render will be appreciated for users on hardware like Raspberry Pi, and older computers which doesnt support vulkan.

Thanks for your work @qwertychouskie and @Benau !

**Comment by qwertychouskie** [comment]
@abchk1234 Although the Pi 4 has a Vulkan driver (and older Pis would use the legacy driver anyways), I agree that keeping a functional GL(ES) 3 renderer available would be the best path forward for a variety of reasons (e.g. pre-Broadwell Intel, pre-600 series Nvidia, and pre-GCN AMD).

**Comment by WALEEDALAREQI** [comment]
I now please send me money 200$in western uonion My neam / WALEED AL AREQI.
country /YEMEN
MOBIL / 967738728352

في السبت، ٢٧ مارس، ٢٠٢١ ٥:٢٨ م Aaditya ***@***.***> كتب:

**Comment by abchk1234** [comment]
Maybe in future everything would be built upon vulkan but for now GL(ES) is still somewhat relevant. It could be used in legacy pipeline or any other way which allows users to experience the joys of supertuxkart on their hardware :) Thanks

**Comment by Benau** [comment]
the gl3 renderer will not stay in the future, sorry about that....

the legacy gl / gles will stay

**Comment by WALEEDALAREQI** [comment]
Check out my fundraising page for Creative Commons Corporation -
https://www.classy.org/fundraiser/3290129

**Comment by Benau** [comment]
A lot of so-called help children campaign is used for money landering anyway 

See you in gitmo

**Pull request closed without merging**
