### PR TITLE
Upstreaming Haiku changes, disabling some graphics defaults

### PR DESCRIPTION
**Pull request by devnexen**
more inline with the OpenGL capacities.

original author @threedeyes

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
Does it use only opengl 2.0?

**Comment by Benau** [comment]
I meant if haiku only has opengl 2.0 those settings can't be used by stk anyway. (Ticking advanced lighting in haiku has no effect)

**Comment by devnexen** [comment]
> Does it use only opengl 2.0?

yes :) I guess more to do with having "sane" defaults.

**Comment by Benau** [comment]
in latest commit I deactivate unusable settings in old renderer so it should cause less confusion 

and I don't think options like 'animated characters' or 'particle effects' will have significant impact on performance

**Pull request closed without merging**
