### PR TITLE
Show boost at startup

### PR DESCRIPTION
**Pull request by qwertychouskie**
#34 seems abandoned, this is (hopefully) the first in a series of PRs to get the same functionality, as #34 has merge conflicts.

### CODE REVIEW

**Comment by auriamg** [comment]
Seems good, I just wonder if we can avoid hardcoding "0.9f" ? I'm not sure where that number comes from

**Comment by qwertychouskie** [comment]
I think it comes from the above line. :)

**Comment by Benau** [comment]
(above line) float Kart::getStartupBoost() const will return 0 if no startup boost is triggered, see kart.cpp:1011

Maybe you meant if (f >= 0.0f)?

Also please don't copy code from elsewhere without studying what it's really do

**Comment by qwertychouskie** [comment]
OK, fixed.

**Comment by auriamg** [comment]
Merged, thanks

**Pull request merged**
