### PR TITLE
Rumble on collisions

### PR DESCRIPTION
**Pull request by Mstrodl**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Mstrodl** [comment]
Code is certainly not ideal at the moment, we should probably reevaluate how to make this work in a way that isn't so hacky...

**Comment by Benau** [comment]
btw Mary not sure if you saw in irc but it builds fail with SERVER_ONLY=ON....

**Comment by Benau** [comment]
I  the SERVER_ONLY build for you! Also made some header changes and fix possible duplicated rumble for networked games 

just 1 question
```c++
#if SDL_VERSION_ATLEAST(1,3,0)
    if (m_haptic)
    {
        SDL_HapticRumblePlay(m_haptic, (strength_low + strength_high) / 2, duration_ms);
    }
    else
#endif
    {
        uint16_t scaled_low = strength_low * pow(2, 16);
        uint16_t scaled_high = strength_high * pow(2, 16);
        SDL_GameControllerRumble(m_game_controller, scaled_low, scaled_high, duration_ms);
    }
```

did you do that for compatibility reason with old SDL2 < 1.3.0? because only reason m_haptic is null is the joystick doesn't support rumble, and calling SDL_GameControllerRumble should not do anything 

and by the way we have a return; earlier in sdlcontroller constructor so I think m_haptic should be initialised earlier too

**Comment by Mstrodl** [comment]
@Benau SDL Haptics I think aren't defined at all in those older SDL versions, so the field won't be there

**Pull request merged**
