### PR TITLE
Fix #4876

### LINKED ISSUE #4876: [UI/UX] Cannot rate addons with keyboard/controller, only mouse/touchscreen
I ran across this while working on https://github.com/supertuxkart/stk-code/pull/4864, you can only give a rating to an addon (or change an existing rating) with a mouse or touchscreen, it's impossible to do with keyboard/controller/etc.

### PR DESCRIPTION
**Pull request by CodingJellyfish**
This is definitely a harsh one...
The implementation is a bit hacky, if admin cares I rewrite.

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.
```

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Now rating is completely broken for me, I can't open the voting dialog at all anymore.

**Comment by CodingJellyfish** [comment]
> Now rating is completely broken for me, I can't open the voting dialog at all anymore.

Could you provide me more specific information?

**Comment by qwertychouskie** [comment]
> > Now rating is completely broken for me, I can't open the voting dialog at all anymore.
> 
> Could you provide me more specific information?

Clicking on the stars in the addon dialog does nothing, nor does pressing Enter.

**Comment by Benau** [comment]
qwerty you need to have an logged-in stk to vote by the way, if not clicking the stars has no effect

**Pull request merged**
