### PR TITLE
Update Wiiuse library to 0.15.4, fixes support for newer Wiimotes on Linux

### PR DESCRIPTION
**Pull request by qwertychouskie**
STK's Wiiuse had some modifications, but I tested and upstream seems to work fine, and fixes the -TR Wiimote.

### CODE REVIEW

**Comment by deveee** [comment]
Update is simple, but did you test it?

**Comment by qwertychouskie** [comment]
Yes, and it works quite nicely, though for some reason Travis doesn't like it.  Also AppVeyor fails but there should be an update to Wiiuse to address this soon.

**Comment by qwertychouskie** [comment]
Hmm.  Both Travis and AppVeyor fail with not finding `wiiuse.h`, but compilation works fine on my system.  @deveee Can you take a look and see why, and push a fix?

**Comment by deveee** [comment]
Previously source files were in lib/wiiuse, now there is a "src" directory. Changing
```include_directories("${PROJECT_SOURCE_DIR}/lib/wiiuse/")```
to
```include_directories("${PROJECT_SOURCE_DIR}/lib/wiiuse/src")```
in STK cmake file fixes compilation for me.

**Comment by qwertychouskie** [comment]
@deveee Any chance of getting this merged soon, since the compilation was fixed?

**Comment by deveee** [comment]
I think that it needs some testing by more people on different systems, but I can't do it myself.

**Comment by MarioCMFlys** [comment]
Tested on Ubuntu-based Linux and works fine

**Comment by hiker** [comment]
Thanks a lot for the patch, and for testing!!

**Pull request merged**
