### PR TITLE
Fix COPYING (including wrapping underline in installer)

### PR DESCRIPTION
**Pull request by qwertychouskie**
See https://github.com/supertuxkart/stk-code/issues/2544#issuecomment-230100514.

### CODE REVIEW

**Comment by auriamg** [comment]
Assigning to hiker. Not sure changing our license file is the best way to deal with this...

**Comment by qwertychouskie** [comment]
Any chance of getting this merged? It's a pretty small change....

**Comment by qwertychouskie** [comment]
Also ping @MTres19, as he handles license stuff (thanks for your work!).

**Comment by auriamg** [comment]
Also, you added "or at your option, any later version.". You definitely should NOT change the term of the license.

**Comment by qwertychouskie** [comment]
@auriamg https://github.com/supertuxkart/stk-code/blob/master/src/main.cpp#L9 includes the "or any later version", which is why I added it.  https://github.com/supertuxkart/stk-code/search?utf8=%E2%9C%93&q=%22or+%28at+your+option%29+any+later+version.%22&type= confirms this is probably correct and that this file is not.  If you want though, I can remove it, though this file probably should match the rest of the code.

**Pull request closed without merging**
