### PR TITLE
MORE ACHIEVEMENTS!!!!!!

### PR DESCRIPTION
**Pull request by SecondLuke242014**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

Make ACHIEVEMENTS 5 for 1 when a player hits karts with bowling cake swatter but 1 race

### CODE REVIEW

**Comment by SecondLuke242014** [comment]
Please accept pull request

**Comment by SecondLuke242014** [comment]
image

**Comment by Benau** [comment]
IMG_20240122_221534_765
IMG_20240122_221545_441

**Comment by SecondLuke242014** [comment]
image
You didn't merge? So idc.

**Comment by mrkubax10** [comment]
... What? It doesn't work this way lol.

**Pull request closed without merging**
