### PR TITLE
Fix #3471

### LINKED ISSUE #3471: Font scaling issues
The rank indicator font is currently upscaled using setScale, and its blurriness is painfully obvious.

Regular text fonts also become blurry when modified with setScale, but afaik this is not really needed anywhere.

### PR DESCRIPTION
**Pull request by CodingJellyfish**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
IDK why don't fix it like this. It's called high res digit font anyway.

### CODE REVIEW

**Comment by CodingJellyfish** [comment]
Before:
屏幕截图 2023-12-19 195316
After:
屏幕截图 2023-12-19 200715

**Comment by Benau** [comment]
Instead of setting 0.4 everywhere you should make a getScalingFactorThree or something like that so that the glyph page itself is scaled up internally. Just like the 'native scale' in iOS

**Comment by Benau** [comment]
This probably too difficult for you so let me do it later

**Comment by Benau** [comment]
something like https://github.com/Benau/stk-code/commit/1e80122c6176b15897175b464839cf0cf501044e but not quite working for the speedometer and the score in overworld, figure out the rest yourself

**Pull request closed without merging**
