### PR TITLE
add polygon radar / optionnal in user_config

### PR DESCRIPTION
**Pull request by luffah**
Hello, 
  This change add a 3D wireframe radar inspired by modern karting games (showing other karts position relative to the camera) with a simplistic design :
  - In all modes, it shows discretly the speed by showing the point reached in 3 ticks, and if you got a cake item, a square is drawn on the target.
  - In ctf mode, it broadly indicate were to go (were is the flag or the base if you already have the flag). 
  - In soccer mode, it shows where is the ball and how it move and the karts that are around the ball (with gradients to represents the distance).
       1. (KART) the **white arrow** (pyramid) shows approximately with distance **where is the ball**;
       2. (KART) around the white arrow there is a square to show with **color** (if red you touch the ball, if blue you miss it, if green it is a perfect alignement) **alignment between kart and ball** (basically saying if you can shoot);
       3. (KART) the **black arrow** (inside white one) shows **where move ball**;
       4. (KART) the **black square** (outside white one) represents **the future shock** - if you want to control the ball you need to keep it small;
       5. (BALL) a green vector shows the trajectory of the ball
       6. (BALL) work with ii. : if the ball is reachable (red or green), a square with same color is drawn on the ball

  The feature still experimental.
  To use it, edit user config.xml file :
```xml
    <!-- Enable radar (show target in ctf and soccer modes) -->
    <show_radar value="true" />
```
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
aimbot?

**Comment by Mrxx99** [comment]
Can you add a video or a screenshot of it in action?

**Comment by luffah** [comment]
Here for CTF (white arrow show the base, blue the blue flag, red the red flag - here the red flag is at base): 
radar-scrot-ctf

For soccer, green line is the ball trajectory, black arrow represents the vector for the ball, white arrow points the ball  (Note : the pyramid - arrow - height depends on the distance of target) : 
radar-scrot

**Comment by luffah** [comment]
I fixed a coordinate (the bumper position)  and fixed some colors, and added settings to allow to change position (height) of the radar. 

But sorry, it doesn't pass appveyor. :(
```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
```

**Comment by luffah** [comment]
Adding target alignment check of bowling ball for all modes.

**Comment by luffah** [comment]
replaced by https://github.com/supertuxkart/stk-code/pull/4220

**Pull request closed without merging**
