### PR TITLE
 Ready, Set, Go! Penalty Removal and Revving #34

### PR DESCRIPTION
**Pull request by TorbenCarrington**
This is a pull request containing all my current work on the bug #34 (task #1090 on sf).

Basically:
- Boost effect added to startup boost.
- Penalty time for accelerating before "Go" has been removed.
- Revving implemented, but sound isn't playing.

I have a pretty good idea of what should be done next, but due to my current situation, I won't be able to commit code for a little while. If someone does not pick this up by the time I am able to return, I will continue work.

### CODE REVIEW

**Comment by deveee** [comment]
This pull request stays here over a year. Is someone interested in it at all?

**Comment by nado** [comment]
I find some things interesting but I dont understand it all (lack of english vocabulary i guess). I like the SFX at startup, it really shows well the startup boost. But what do you want to change in revving ?

**Comment by Benau** [comment]
Actually he deleted his fork, not sure if he wants to continue to work on it...

Or should we close this pull reqest?

(Here goes meme.jpg, lol)

**Comment by nado** [comment]
I saw the deletion. But i still dont understand what was his goal.

**Comment by qwertychouskie** [comment]
I like the idea of a Mariokart-like start, but, unfortunately, I could not figure out how to test this PR, as the layout of src/karts/controller/player_controller.cpp seems to have changed.

**Comment by qwertychouskie** [comment]
Can this be closed, as it is obsoleted by #2586 and #2588?  The only thing different about this PR is an unsuccessful attempt at sound (which I hope to have a working version soon).  This PR also has conflicts.

**Comment by qwertychouskie** [comment]
Can this be closed as obsolete?

**Comment by deveee** [comment]
This pull request is 4 years old and it looks that noone is interested in it, so I'm closing it as invalid.

**Pull request closed without merging**
