### PR TITLE
Randomizing spawn points for battle mode #3620

### PR DESCRIPTION
**Pull request by Aleman778**
This PR changes the kart status struct to include a spawn id that can be used when setting the start transform. 

This fixes the issue #3620 for playing offline but it may still remain for online play. I wasn't able to fix this issue for online play.

## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
Maybe std shuffle starting transform for offline battle?

**Comment by Aleman778** [comment]
> 
> 
> Maybe std shuffle starting transform for offline battle?

Yes that would work I didn't think about that! Any ideas for implementing this on the server?

**Comment by Benau** [comment]
You dont need to, starting position is already randomized in online games

**Comment by Aleman778** [comment]
I have updated the code to shuffle the starting transforms and removed the code for the previous approach. I was not able to check if the given world was online or not so I had to check if the first player has a global id of -1 to ensure that shuffle is not done online.

**Comment by Benau** [comment]
NetworkConfig::get()->isNetworking()?

**Comment by Aleman778** [comment]
That works!

**Comment by Benau** [comment]
also can u remove newline changes for race_manager.cpp?

**Comment by Aleman778** [comment]
Ops! Forgot to do that before.

**Pull request merged**
