### PR TITLE
thai translate(th.po)

### PR DESCRIPTION
**Pull request by annopnod**
thai translate is not complete (work in process)

### CODE REVIEW

**Comment by Benau** [comment]
https://www.transifex.com/supertuxkart/supertuxkart/language/th/
Click supertuxkart.pot

And then click upload file

**Comment by Benau** [comment]
you actually leave transifex thai team... why you are doing that?

**Comment by Alayan-stk-2** [comment]
Translations are handled through STK's page at Transifex. Directly merged translation changes would be overwritten later on when translations are pulled from there.

**Comment by annopnod** [comment]
> you actually leave transifex thai team... why you are doing that?

sorry i clicked wrong button.i rejoin it
if font not work use th-sarabun is public license

**Comment by Benau** [comment]
not sure deve can readd annopnod as thai member instantly lol

**Pull request closed without merging**
