### PR TITLE
Fix capitalization of categories, fixes #4622

### LINKED ISSUE #4622: Change "standard" to "Standard"
## Description
The string "standard" shoud be "Standard" multiple places.

## Steps to reproduce
Start STK
Select singleplayer
Bottom have 3 strings: "All", "standard", "Add-Ons"

Select a cart
Select normal race.
"standard" appear again.

Go back
Select Battle
"standard" appear again.

## Configuration
SuperTuxKart-1.3-rc1-installer-x86_64.exe
1.3-rc1
official binary

### PR DESCRIPTION
**Pull request by qwertychouskie**
- Fix capitalization of "Standard" in kart and track selection screens
 - Fix both "All" and "Standard" in random GP screen
 - Code style/documentation/consistency improvements

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
No changing of kart / track.xml is required?

**Comment by qwertychouskie** [comment]
No changes required, the change is purely visual.

**Comment by Benau** [comment]
```xml
#. I18N: arena group name
#. I18N: track group name
#: src/states_screens/arenas_screen.cpp:80
#: src/states_screens/easter_egg_screen.cpp:143
msgid "standard"
msgstr ""
```

**Comment by qwertychouskie** [comment]
Fixed and force-pushed

**Pull request merged**
