### PR TITLE
Show a message once a goal is made in soccer

### PR DESCRIPTION
**Pull request by risostk**
Hi, once a goal is made in soccer, it will show who made the goal and if it is an own goa, see figures below. I also made a log of goals on servers. Hope you like it. 
Screenshot from 2020-05-29 22-52-52
Screenshot from 2020-05-29 22-52-23

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
i don't like tracking server

**Comment by risostk** [comment]
so you want to remove the server log code?

**Comment by Benau** [comment]
yes please 

also not sure you think the big "GOAL!" message is now useless...

**Comment by risostk** [comment]
emmm... Personally, I would like to keep the "GOAL!" in the middle. Not all players want to read the bubble message. The "GOAL!" in the middle provides a simple and direct message.

**Pull request merged**
