### PR TITLE
Integrate Irrlicht with STK source code

### PR DESCRIPTION
**Pull request by SuicSoft**
Since in the future Antarctica will be a stand-alone OpenGL engine (see #2358) we should move Irrlicht into the main source code folder since it is our own version and not just a library.

### CODE REVIEW

**Comment by deveee** [comment]
Omg but as I see you just deleted irrlicht?

**Comment by SuicSoft** [comment]
@deveee Irrlicht is now in https://github.com/SuicSoft/stk-code/tree/integrate_irrlicht/src/stkirrlicht.

**Comment by auriamg** [comment]
I know you're well-intended, but this doesn't help us. Just because we would like to make the code modular doesn't mean we need to put it all in the same folder - in fact, in which folder resides the code is probably the least important aspect, making the code more modular would be much more important than just moving stuff around for no practical again. For future contributions, I strongly suggest you discuss with us before attempting large scale changes

**Pull request closed without merging**
