### PR TITLE
Fix angelscript build on non-x86 arches - fixes #2119 and fixes #2194

### LINKED ISSUE #2119: [angelscript] won't compile on armv7l
```
CMakeFiles/supertuxkart.dir/src/animations/ipo.cpp.o CMakeFiles/supertuxkart.dir/src/animations/animation_base.cpp.o CMakeFiles/supertuxkart.dir/src/animations/three_d_animation.cpp.o  -o bin/supertuxkart -rdynamic -lpthread lib/bullet/libbulletdynamics.a lib/bullet/libbulletcollision.a lib/bullet/libbulletmath.a -lenet lib/glew/libglew.a lib/irrlicht/libstkirrlicht.so lib/angelscript/projects/cmake/libangelscript.a -lcurl -logg -lvorbis -lvorbisfile -lopenal -lGLU -lGL -lX11 -lXext -lXrandr -lfribidi -lwiiuse -lpng -ljpeg -lz -Wl,-rpath,/builddir/build/BUILD/supertuxkart-0.9/build/lib/irrlicht: 
lib/angelscript/projects/cmake/libangelscript.a(as_callfunc.cpp.o): In function `CallSystemFunction(int, asCContext*, void*)':
/builddir/build/BUILD/supertuxkart-0.9/lib/angelscript/source/as_callfunc.cpp:492: undefined reference to `CallSystemFunctionNative(asCContext*, asCScriptFunction*, void*, unsigned long*, void*, unsigned long long&)'
collect2: error: ld returned 1 exit status
```

Full log: http://koji.fedoraproject.org/koji/getfile?taskID=9554098&name=build.log

### LINKED ISSUE #2194: STK 0.9 fails to build on armel/armhf/arm64/ppc64el/s390x
STK 0.9 (just uploaded today to Debian) fails to build on a variety of non-i386/amd64 architectures in Debian sid; see [here](https://buildd.debian.org/status/package.php?p=supertuxkart&suite=unstable) for build status and logs (you can click on any of the rows under the "Status" column for the entire log for that arch). Note that STK 0.8.1 built fine on all archs supported by Debian.

All of the build failures have this in common:
```
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp: In function 'asQWORD X64_CallFunction(const asQWORD*, int, funcptr_t, asQWORD&, bool)':
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%rcx' in 'asm'
     "%rdi", "%rsi", "%rax", "%rdx", "%rcx", "%r8", "%r9", "%r10", "%r11", "%r15");
                                                                                  ^
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%rdx' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%rax' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%rsi' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%rdi' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm7' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm6' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm5' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm4' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm3' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm2' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm1' in 'asm'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_x64_gcc.cpp:144:82: error: unknown register name '%xmm0' in 'asm'
```

Does angelscript require porting assembly to various non-x86 archs? The weird thing is that STK 0.9 actually builds fine on some non-x86 archs, e.g. mipsel, and I'd be kinda surprised if some piece of software supported mips but not arm these days. However, it does in fact look like angelscript has been ported to arm (lib/angelscript/source/as_callfunc_arm.cpp); why is x86 assembly being used in the arm build then?

It seems to me that this is probably related to the build system somehow, but I'm not all that familiar with cmake; does anyone know what might be going on here?

### PR DESCRIPTION
**Pull request by jcowgill**
This is my fix for #2119 and #2194. I have compile tested it on x86_64 and mips64el. Incredibly I have no ARM hardware so I am currently building it there with QEMU. That'll probably take at least another hour though.

----
For the build failures on 64-bit arches, angelscript was using `__LP64__` to test for x86_64. Use the correct define instead.

For ARM architectures, ensure the native function calling file is built on all ARM arches and not just when building for android.

### CODE REVIEW

**Comment by jcowgill** [comment]
The original ARM build failed, but adding `-Wa,-mimplicit-it=always` to the compile options for the assembly file makes it build successfully.

**Comment by auriamg** [comment]
Thanks for the pull requests, though since some parts affect angelscript directly, I will try to get these changes upstream

**Comment by Vincent-C** [comment]
@jcowgill It looks like only armel FTBFS now:

```
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_arm_gcc.S: Assembler messages:
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_arm_gcc.S:88: Error: selected processor does not support ARM mode `blx r4'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_arm_gcc.S:136: Error: selected processor does not support ARM mode `blx r4'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_arm_gcc.S:183: Error: selected processor does not support ARM mode `blx r4'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_arm_gcc.S:221: Error: selected processor does not support ARM mode `blx r4'
/«PKGBUILDDIR»/lib/angelscript/source/as_callfunc_arm_gcc.S:258: Error: selected processor does not support ARM mode `blx r4'
```

Not knowing how portable the ARM assembly in angelscript actually is...perhaps it's best to just use the `AS_MAX_PORTABILITY` define for armel? Is there a way to distinguish armel from armhf/arm64?

@auriamg Not sure if you saw @jcowgill's reply in #2194 or not, but that page does mention that angelscript is supported for arm, amongst a variety of other CPU architectures.

**Comment by jcowgill** [comment]
Lovely, `blx` is an ARMv5 instruction and Debian armel is only ARMv4t. Looking at the source (bear in mind I don't know ARM very well), it also uses a lot of `ldmia ... pc` instructions which don't cause the correct Thumb mode change on ARMv4t, but do on ARMv5. So I think the best solution is to just disable the ARM assembly parts on v4 until they can be fixed (if that ever happens).

> Is there a way to distinguish armel from armhf/arm64?

Yes `__ARM_ARCH_4T__` is defined on armel, but not the others. I'll push a fix to disable it there in a minute.

**Comment by hiker** [comment]
@auriamg  This sounds like a patch to be potentially useful upstream (in case that they want to support those platforms), but not for us at this stage then. Can it be closed?

**Comment by auriamg** [comment]
Given that STK doesn't support those architectures then I would agree this should be submitted upstream, not here. Closing this PR

**Pull request closed without merging**
