### PR TITLE
rank by greatest time if points equality in Follow the leader

### PR DESCRIPTION
**Pull request by courbe**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
In Follow the leader mode the greatest cumulated time is a better critera for deciding the rank if several karts have the same total of points. It was set to the less cumulated time as expected for the Grand Prix and Time Trial modes.

### CODE REVIEW

**Comment by Benau** [comment]
static variable should be used because it's the same for all data

**Comment by Benau** [comment]
Or call race manager get minor mode == ftl inside sorting, no var is needed at all

**Comment by courbe** [comment]
The call is now done from inside sorting (sorry for having missed the static get function in the hpp file).

**Pull request merged**
