### PR TITLE
Skidding fixes

### PR DESCRIPTION
**Pull request by qwertychouskie**
Mainly for when the kart is in the air.

### CODE REVIEW

**Comment by Arthur-D** [comment]
Not sure we want to fix this - it's come up before and then it was decided to keep it as a feature. While skidding in the air is not realistic it allows for more control and you can keep accumulating skid bonus even if you're slightly in the air at some point.

**Comment by qwertychouskie** [comment]
If you want, I could separate this PR into two parts: the visual and auditory fixes; and the physics changes.

**Comment by Arthur-D** [comment]
Maybe you could begin with describing it. "Skidding fixes - Mainly for when the kart is in the air." What is this pull request fixing, and why is it needed?

**Comment by qwertychouskie** [comment]
The changes to effects were separated into https://github.com/supertuxkart/stk-code/pull/2941.

**Comment by qwertychouskie** [comment]
Closing as the physics changes don't seem to be wanted (I have to admit I do use skidding in the air :).  See https://github.com/supertuxkart/stk-code/pull/2941 for effects changes.

**Pull request closed without merging**
