### PR TITLE
Ghost replay selection fix

### PR DESCRIPTION
**Pull request by Fantasmos**
To fix: https://github.com/supertuxkart/stk-code/issues/3034

Example: https://i.imgur.com/WRniypS.png 

A simple solution to this issue, alternative solutions are to make it " " instead of "Unknown."

### CODE REVIEW

**Comment by Fantasmos** [comment]
Changed it to be language neutral and instead have no number: https://i.imgur.com/WEwZD4m.png

**Comment by auriamg** [comment]
Okay, but why must it be a whitespace character? Couldn't it just be an empty string "" ?

**Comment by auriamg** [comment]
What I was trying to say in my previous comment is : I guess I'd prefer to understand the root of the problem, rather than patching it locally by adding spaces. If you can't find the root of the issue I guess that's still better than nothing though

**Comment by Fantasmos** [comment]
@auriamg  The issue is that there are three vectors that are inserted values for each replay, however when a username doesn't exist it doesn't insert a value into the column. Therefore when it comes to display it, since there are less values than other columns fucky stuff happens. 

Therefore having strings be inserted in place of actual values is a solution, and it doesn't disrupt existing setups or add more unecessary load. The only other fix I can think of is the parameter that's "false" may have other inputs or settings for this scenario.

**Comment by auriamg** [comment]
Merged, thanks

**Pull request merged**
