### PR TITLE
Add padding support (Thanks to QwertyChouskie)

### PR DESCRIPTION
**Pull request by CodingJellyfish**
## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
The paddong support mainly by QwertyChouskie.
After that the skin of Qwerty's will be supported.
The old bug in the comment is fixed.

### CODE REVIEW

**Comment by dumaosen** [comment]
Qwerty help!
The tabs doesn't show texts in my code. Have u got the solution of it?

**Comment by Alayan-stk-2** [comment]
As this isn't really useful for the base skin, but mostly for qwerty's skin, this PR needs not only to be tested for not breaking the current themes, but also for enabling qwerty's to work. It would be useful to provide a link to an up-to-date version of qwerty's skin to test this.

**Comment by dumaosen** [comment]
See this: https://github.com/NeoSTK/stk-modern-skin

**Comment by qwertychouskie** [comment]
I appreciate the PR, but there's still one known bug in my code: the border spacing doesn't take border scaling into account, so the spacing will be wrong if there is significant scaling.  Don't worry, I haven't forgotten this code, just been a bit busy with work. :)

**Comment by Benau** [comment]
is it minor fix? otherwise i may just merge this pr....

**Comment by qwertychouskie** [comment]
I'll try to get the code fully fixed as quickly as possible.

**Pull request closed without merging**
