### PR TITLE
Some improvements for soccer AI spinner

### PR DESCRIPTION
**Pull request by dumaosen**
## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
No1: Move red & blue AI num to race_manager
No2: Improve riso's code
No3: Give a bigger space in track info so that spinners won't be out-of-box

### CODE REVIEW

**Comment by risostk** [comment]
Hi maosen, You forgot to remove
UserConfigParams::m_soccer_red_ai_num
UserConfigParams::m_soccer_blue_ai_num
in user_config.hpp

**Comment by dumaosen** [comment]
> Hi maosen, You forgot to remove
> UserConfigParams::m_soccer_red_ai_num
> UserConfigParams::m_soccer_blue_ai_num
> in user_config.hpp

They are still used to store the last setting

**Comment by dumaosen** [comment]
you guys didnt add my name to changelog for it

**Comment by Benau** [comment]
Allow to choose the number of AI per team in soccer, by risostk (and dumaosen)?

**Pull request merged**
