### PR TITLE
"Brake" -> "Brake/Reverse" in english and french #3858

### PR DESCRIPTION
**Pull request by GuillaumeBft**
## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
you only need a commit with renameRow(actions, i++, _("Brake/Reverse"), PA_BRAKE);

**Comment by Yionnara** [comment]
If I do what you say, we'll see Brake/Reverse in every language (i know that cause i test before changing lang files). "Brake/Reverse" in your code part is not a string only, its also an ID in PO files to switch it on other languages.

**Comment by Yionnara** [comment]
that explains 'msgid "Brake/Reverse"' cause i did what you advice me to do

**Comment by Benau** [comment]
we generate po files using data/po/update_pot.sh, also your pr includes merged commits.

**Comment by Yionnara** [comment]
Okay it explains à lot ^^'

**Comment by Yionnara** [comment]
I 'll chrck that as soon as I can thx

**Comment by Benau** [comment]
9e0da6a

**Pull request closed without merging**
