### PR TITLE
Added documtation for CentOS/RHEL/Mageia/OpenSUSE

### PR DESCRIPTION
**Pull request by jpenguin**
Just added dependency instructions

### CODE REVIEW

**Comment by Benau** [comment]
btw you can idle on our irc channel to know when to update your servers! (you are tuxpeng?)

**Comment by jpenguin** [comment]
Thanks

Yes, I'm going to just keep and update my PLAYSTK servers (AWS), probably shutdown the others

**Comment by Benau** [comment]
Deve wanna merge? Maybe not sure glu-devel is needed...

**Comment by jpenguin** [comment]
It used to compile without it. When I tried to compile on Friday, it couldn't find glew without it

**Comment by deveee** [comment]
I will look at this in next few days. Glu shouldn't be needed because we explicitly want OPENGL_gl_LIBRARY in cmake and our static package is compiled without it. But having it installed doesn't hurt anyway.

**Comment by jpenguin** [comment]
I have opensuse tumbleweed installed on my computer, cmake kept saying it couldn't find glew- I made sure the development packages were installed, then I installed flu & it found glew

**Pull request merged**
