### PR TITLE
add message freguency limit in chat #3893

### PR DESCRIPTION
**Pull request by GuillaumeBft**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

In chat, ensure that for a person writing more than 3 consecutive messages (less than 5s between 2 messages) prevents display an other message from him while the next 5 seconds.

### CODE REVIEW

**Comment by dumaosen** [comment]
please make it configurable in server.xml,  or i can help you after merge.

**Comment by kimden** [comment]
This is too strict in my opinion. I would prefer character limit per some time interval like 5s, but not that strict. And yes, probably the best option is making it configurable on a server.

**Comment by GuillaumeBft** [comment]
I will try to make it configurable in server.xml. By making it configurable on a server @kimden , you mean like an option for the owner for enable or increase/decrease the timer on the server lobby ?

**Comment by kimden** [comment]
I guess making it configurable (and turnable on/off) in server config is sufficient, I don't think this setting changes too often.

**Comment by GuillaumeBft** [comment]
PreventSpam
What do you think about adding a gauge like this ?

**Comment by Benau** [comment]
no we don't even want that in server configuration screen, the server configuration screen is meant to be simple

just add that to server config.xml

**Comment by Benau** [comment]
...let me add this for you is even quicker

**Pull request merged**
