### PR TITLE
Add rename config option

### PR DESCRIPTION
**Pull request by GuillaumeBft**
Issue #3408
Add a button for rename a configuration.

RenameConfigOption

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
You probably need xmlDe/Encode to deal with " character

**Comment by GuillaumeBft** [comment]
Understood, I'm on it

**Comment by Benau** [comment]
maybe m_config_name can be stringw so you don't need to utf8ToWide everytime...

**Comment by GuillaumeBft** [comment]
Yes, I hesitated to do it, I correct it

**Comment by Benau** [comment]
there is a .empty() for string(w) instead of size() != 0

also i think you you just setConfigName without c_str()

**Pull request merged**
