### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by qwertychouskie**
I'm at home sick, so decided to finally finish this.  I'd still like to see a proper icon designed at some point that works well at small sizes, but at least this one doesn't scream 0.7-0.8 STK.  Also, this should fix the potential for blurry icons on large/HiDPI screens, as icons were exported all standard platform resolutions (including the HiDPI-specific sizes for macOS).

This does increase the size of /data by ~1.3MB, though most of the size is the Windows-specific `.ico` files and source SVGs, which can be excluded in the Android/iOS releases to save space.

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
not sure alayan like these new icon

**Comment by Alayan-stk-2** [comment]
+ The current icons are ugly, these are better
- This doesn't match the main style of the game, only the modern skin style

If someone designed new cool icons that match better the main style (or are less style-specific than these), I'd merge them over, but I guess in the meantime for the next release this is better than staying with the current ugly icon.

**Comment by Benau** [comment]
------------------------------------


(For free hong kong stk edition)

**Comment by 7wells** [comment]
Hi benau,

The pig is really cute (you often use it as emoji, too). Is there a name, will it become an official hero in STK?

**Comment by Benau** [comment]
Not sure  or qwerty can  new stk icons based on the tux rtt.png

**Comment by Benau** [comment]
https://cdn.discordapp.com/attachments/376132246161326081/737106631820574770/supertuxkart.xcf in case someone need it, i  a shadow with gimp btw

**Comment by Benau** [comment]
if alayan likes benau idea for new tux kart rendering as icon then i will go ahead...

**Pull request closed without merging**
