### PR TITLE
Angelscript 2.32.0

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by qwertychouskie** [comment]
All checks have failed
1 failing check
continuous-integration/travis-ci/pr — The Travis CI build failed

Hmm... It seems Clang does not like your code...

**Comment by ignatenkobrain** [comment]
@qwertychouskie actually it's bug somewhere in angelscript.

**Comment by auriamg** [comment]
ok thanks, but I don't think we will merge if the build is failing...

Also, is there a specific reason for updating, or just the good practice of keeping up to date with no specific reason?

**Comment by ignatenkobrain** [comment]
@auriamg I will report this issue to angelscript upstream, so just don't close this (once we will have fix, I will push it here).

About update.. In Fedora we are using system-wide angelscript and we are keeping it up2date so it was a bit problem when STK stopped compiling. Also when new version of angelscript is supported in upstream it is always better.

**Comment by qwertychouskie** [comment]
Is there a link for the upstream report?

**Comment by ignatenkobrain** [comment]
some quick investigation:
```
#ifdef AS_CAN_USE_CPP11
...
#include <type_traits>
...
#endif
```

I guess we must define it when compiling, if CI will fail again - I will do that (we use c++11, so it's okay)

**Comment by ignatenkobrain** [comment]
@qwertychouskie I was not able to find bugtracker in upstream, so I sent bugreport to main developer via mail.

**Comment by ignatenkobrain** [comment]
@qwertychouskie actually it is a bug in clang: https://llvm.org/bugs/show_bug.cgi?id=25880

**Comment by deveee** [comment]
I noticed a fix for clang build, though I didn't check it yet:
https://sourceforge.net/p/angelscript/code/2335/

**Comment by ignatenkobrain** [comment]
So, I rebased this to newest 2.31.2 which should fix all secondary architectures and build with this version of clang.

**Comment by ignatenkobrain** [comment]
So, it still fails...
```cpp
/home/travis/build/supertuxkart/stk-code/lib/angelscript/source/as_string_util.cpp: In function ‘asQWORD asStringScanUInt64(const char*, int, size_t*, bool*)’:

/home/travis/build/supertuxkart/stk-code/lib/angelscript/source/as_string_util.cpp:189:28: error: ‘UINT64_MAX’ was not declared in this scope

/home/travis/build/supertuxkart/stk-code/lib/angelscript/source/as_string_util.cpp:216:29: error: ‘UINT64_MAX’ was not declared in this scope
```

but this is due upstream needs c++11 std as only its version defines UINT64_MAX in `cstdint`..

**Comment by auriamg** [comment]
Indeed, both Clang and vc++ builds fail for different reasons :/ they should work before we upgrade.

**Comment by qwertychouskie** [comment]
@ignatenkobrain It may be worth a try using the latest WIP (http://www.angelcode.com/angelscript/wip.php), as relying on an old bundled version could cause headache for packagers packaging 0.9.3.

**Comment by nado** [comment]
I believe I made a working copy for travis by installing newer versions of gcc/clang back in the day.
Never got any reply about that from @ignatenkobrain

**Comment by ignatenkobrain** [comment]
Hopefully now it should work (I also updated angelscript to newly released 2.32.0)

**Comment by ignatenkobrain** [comment]
@qwertychouskie @nado @auriamg @deveee Yeah, it worked!

Feel free to re-review this PR and sorry for such long delay ;)

**Comment by deveee** [comment]
Modifications in .travis.yml are not needed, because as I see travis already uses clang 5.0.

I tested and it compiles for me without issues on gcc 4.7.2 and clang 4.0.

@auria are you ok with clang >= 4.0? If so, then I would merge it.

It only needs to revert .travis.yml and fix cmake warning in angelscript CMakeLists.txt:
```
if(NOT (CMAKE_MAJOR_VERSION VERSION_LESS 3))
  cmake_policy(SET CMP0048 OLD)
endif()
```

**Comment by auriamg** [comment]
@deveee sounds good to me, ok

**Comment by deveee** [comment]
Already commited in https://github.com/supertuxkart/stk-code/commit/aec7ca0ce911544e18722cf6387050acf347f852
Thanks!

**Comment by deveee** [comment]
It looks that travis with clang 5.0 fails even if compilation with clang 4.0 works on my linux, so that it depends on something more than just clang version (libstdc++ ?)

It should be possible to revert 
https://sourceforge.net/p/angelscript/code/2278/

I already asked Andreas if it's safe and if there is a better fix.

**Pull request closed without merging**
