### PR TITLE
SVG support

### PR DESCRIPTION
**Pull request by risostk**
Hi, this PR provides SVG support for STK, to address issue #4066. As large screens become more and more popular, bitmap icons will look blur on them. Having a higher resolution icon will increase the size of the assets. Also need to deal with the downscaling issue mentioned by qwertychouskie. SVG can provide a solution for this.

In stkskin.xml, you can specify .svg files. Also, you can put SVG files in data/gui/icons, so STK can load the SVG file. Note that the SVG file should have the same name as the PNG file. There is no need to set a specific default size for the SVG, the code will take care of the scaling. You just need to have the correct aspect ratio.

The size of the rasterized image depends on the screen size. I used a phenomenological equation: 0.21*screen_height + 30. This gives icon size for different screen resolutions:
- 720p: 181x181 pixels
- 1080p: 257x257 pixels
- 4K: 484x484 pixels
- 5K: 635x635 pixels
- 8K: 937x937 pixels

I currently don't have access to my 5K screen, so not able to test it on a 5K resolution. I will do the test once I have access. Anyone with a large screen is welcome to test!

I haven't completely tested the SVG version of the modern skin, due to a few missing SVG files. But for the screen without any missing icons, it displayed correctly, see below. I also tested it with a skin made by myself. It worked well. I will test the modern skin once I have all the files. The modern (SVG) is a good test case.

I have tested the compilation on Linux, Android, and MacOS, without any problem. Hope anyone with access to Windows and iOS can help to check the compilation. I will fix the compilation error if there is any.

I used the nanosvg provided in SDL2_Image-2.0.5 as parser and rasterizer. I manually merged several PRs.

I am pretty happy with it. Any comments are welcome! Thanks Benau for helping with my questions!

Screenshot from 2020-06-06 16-12-01
Screenshot from 2020-06-06 16-18-04

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
There is quite a lot of memory leak (char* x = new and no delete) 

Also i think you better make the image power of 2 for (gles 2.0) legacy pipeline, check CreationParams.legacydevice because old gl doesn't support non power of 2 texture

**Comment by risostk** [comment]
> There is quite a lot of memory leak (char* x = new and no delete) 
> 
> Also i think you better make the image power of 2 for (gles 2.0) legacy pipeline, check CreationParams.legacydevice because old gl doesn't support non power of 2 texture 

Hi, any idea how to get a pointer to CreationParams in CImageLoader?

**Comment by Benau** [comment]
hmm maybe it's better to let me do the legacy support for u

**Comment by risostk** [comment]
Cool, I'll just push the delete. Thanks!

**Comment by Benau** [comment]
new char[x], delete[] data

**Comment by risostk** [comment]
>  new char[x], delete[] data

sorry, my bad

**Comment by risostk** [comment]
Also benau, do you think it is possible to load exactly the required size of icons (non-legacy case), so not simply determined from the screen size? As far as I understand, STKTexture::reload (where images are loaded) is called before RibbonWidget::add (where the optimal size is determined).

**Comment by qwertychouskie** [comment]
> As far as I understand, STKTexture::reload (where images are loaded) is called before RibbonWidget::add (where the optimal size is determined).

Is there any particular reason that this needs to be the order?  Seems like it could be made so that `STKTexture::reload` is inside `RibbonWidget::add`, so RibbonWidget::add` calls `STKTexture::reload` once sizes are determined, but still has the textures available to it when it starts to do stuff with the textures.

**Comment by risostk** [comment]
> > As far as I understand, STKTexture::reload (where images are loaded) is called before RibbonWidget::add (where the optimal size is determined).
> 
> Is there any particular reason that this needs to be the order? Seems like it could be made so that `STKTexture::reload` is inside `RibbonWidget::add`, so RibbonWidget::add`calls`STKTexture::reload` once sizes are determined, but still has the textures available to it when it starts to do stuff with the textures.

I notice that RibbonWidget::add is called once a screen is shown/switched. But STKTexture::reload is called only once for each icon. I guess STK did this because reloading images is time-consuming?

**Comment by qwertychouskie** [comment]
Most icons should only be shown once per screen, though if there are performance issues, keeping a copy of each icon/resolution pair in memory as a "cache" to copy from instead of re-rasterizing duplicate icon/resolution pairs each time could solve it.

**Comment by Benau** [comment]
too many things need to be changed just for it...

**Comment by Benau** [comment]
btw can you give me the modern skin data folder in svg so i can test

**Comment by risostk** [comment]
Hi, you may notice that rating_star.svg is not rendered correctly. That is due to "paint-order:stroke fill markers". Seems this painting order is currently not supported. To have a correct rendering with this implementation, you have to paint stroke after fill. This icon may need some redraw. Sorry for this @qwertychouskie .

**Comment by risostk** [comment]
Hi, I modified the rating_star.svg to have it rendered correctly.
[rating_star.svg.zip](https://github.com/supertuxkart/stk-code/files/4748835/rating_star.svg.zip)

**Comment by Benau** [comment]
,,,where is the complete data/skins/modern.zip with only svg icons...

**Comment by risostk** [comment]
> ,,,where is the complete data/skins/modern.zip with only svg icons...

I don't have the complete data. Several icons (represent different states, i.e. pressed, unpressed) do not have an SVG source. Qwertychouskie got those PNGs with GIMP. Let me just send you what I have. I simply duplicated the existing SVG for the missing icons. We need to wait for qwertychouskie for the complete set, or if I have time, I can fix them, probably in the weekend. Anyway, it should be good enough to test the code.

**Comment by risostk** [comment]
[modern_svg.zip](https://github.com/supertuxkart/stk-code/files/4749824/modern_svg.zip)
Here is the SVG skin. Notice that there are still a few PNGs used.

**Comment by risostk** [comment]
Hi benau and qwertychouskie, I have drawn all the missing icons. There you go.
[modern_svg.zip](https://github.com/supertuxkart/stk-code/files/4755786/modern_svg.zip)


There is still one problem. The button in the options screen is the tab image in the modern (SVG) skin, but in the modern skin it is the button image, see the following figure:

Screenshot from 2020-06-09 20-43-22
Screenshot from 2020-06-09 21-01-39

BTW, why up_down.png and wing_mirror.png are both in the icons/ folder and the icons/android/ folder?

**Comment by qwertychouskie** [comment]
I'll work on this this evening.  I suspect that `resolution_of_the_SVG * upper_power_of_two(round(1080 * monitor_vertical_res))` might give a better result, especially for e.g. box borders, and I'd like to try to get rendering at native resolution working for standard icons (basically anything that doesn't use advanced stretching).

**Comment by risostk** [comment]
Thx! If you try the latest code, I have disabled scaling of the box, so box border looks nicer. We could provide a list of icons that needs stretch in CImageLoaderSVG.cpp. That's a good idea!

**Comment by risostk** [comment]
Updated the SVG skin. Now modern (SVG) and modern should visually be the same.
[modern_svg.zip](https://github.com/supertuxkart/stk-code/files/4767512/modern_svg.zip)
Log: update options_language.svg, tab_vert.svg, tab_vert_focus.svg

**Comment by 7wells** [comment]
Hi and thanks a lot for this update! If I want to test/use these changes, how do I do this? Will the above described changes go into the next git versions for all distros?

In general, I can compile STK for Android (have not yet tested compilation for Linux and Windows).

**Comment by risostk** [comment]
> Hi and thanks a lot for this update! If I want to test/use these changes, how do I do this? Will the above described changes go into the next git versions for all distros?
> 
> In general, I can compile STK for Android (have not yet tested compilation for Linux and Windows).

Hey! Thanks for your interest. You can pull the code using:
```
git remote add risostk https://github.com/risostk/stk-code.git
git checkout --track -b svg_support risostk/svg_support
```
Then compile the code as normal. Let me know if you have any problems.

**Comment by risostk** [comment]
Hi qwertychouskie, I do not quite understand your equation. Here is how I get mine. I measured the size of the big icons in the main menu, and did a linear fit to the data. Then I make the size of the icons slightly bigger. Here is the data. I didn't measure the data for larger resolutions. But I guess it won't be a big problem.
icon_screen_data

**Comment by qwertychouskie** [comment]
`resolution_of_the_SVG * upper_power_of_two(round(1080 * monitor_vertical_res))`

The idea of taking `resolution_of_the_SVG` into account is that icons that only display small will not be rendered at a very high resolution, while large icons (main menu, etc.) will.  The current icon sizes are optimized for a 1080p-ish screen, so rendering at these sizes on these screens, and rendering a POT larger on higher-res screens will give a good result for all icons, and keep VRAM consumption under control (tiny icons won't render super high-res).  (And keeping everything POT keeps things simple on e.g. GLES2.)

That being said, I'm currently experimenting with adding preferred h/v resolution hints to the relevant calls (`getTexture()`, `loadImage()`, etc.) so that SVGs can be loaded at their native resolution when possible.

**Comment by risostk** [comment]
Thanks! Now I understand. Then we need to have the default size proportional to the final one. For different screen resolution we just scale them all by a same factor.

**Pull request merged**
