### PR TITLE
Add soccer support to show karts held powerups

### PR DESCRIPTION
**Pull request by luffah**
This patch add karts icons and powerups in soccer mode.
~~Kart list is sorted by best scorers of the match.~~ (removed)
Kart list is sorted by team.
A flag is added behind the kart icon to show team.
The name of the kart is on the list (because almost everybody use Wilbert -and Hexley- kart in soccer mode)
 
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
You need to sort with scores data each time otherwise info will be missing when spectate in network games

**Comment by luffah** [comment]
I didn't want to synchronize this information on network without a proper discussion...

**Comment by Benau** [comment]
The scorers data are already synchronized before starting spactating

**Comment by Benau** [comment]
Though seeing others items dont have so much usefulness because there is no bubblegum in soccer...

**Comment by luffah** [comment]
> You need to sort with scores data each time otherwise info will be missing when spectate in network games 

I don't understand. Setting karts positions at the beginning the 'update' function in soccer_world.cpp using m_scores don't do the job ?   (if you have a hint...)

**Comment by luffah** [comment]
> Though seeing others items dont have so much usefulness because there is no bubblegum in soccer...

I think it could useful, but not at side like in race mode, but above the kart (or in map) to know who will shot at you.

**Comment by jijn** [comment]
I think this is useful. Knowing what other players have can help to take actions earlier, and to have better collaboration. If I know my teammate has a bowling ball and in a better position than me, I would give the ball to her/him.
Sorting the scores is not necessary, IMO. Showing above the kart is a better idea. Maybe plot the icons above the name?

**Comment by luffah** [comment]
After meditating, i think the most useless (in soccer mode) is to see kart list sorted by scoring.

It occults the fact that there are defenser. In fact, it could be usefull to add many critera to measure the player performance (too complex for now):
   - ball control time
   - shots to the goal
   - successed goals
   - stopped goals

Moreover, if you want to check easily what is preparing a player (in a team), her position shall not change on the monitor.

Therefore, i sort the players by team (and id). The opposing team members are shown first to respect the position on the minimap at start.

hpu-scrot

**Comment by luffah** [comment]
Note for future ranking devs. 
Given position is modified to order players list.

If you use position for ranking,
position shall be set again at the end of the match.
 `world->setKartPosition(n);`  where n is 1 for players of winning teams varying on soccer ranking criterion; n representing either a rank or an achievement (best goaler, best defenser...).

**Comment by remihb** [comment]
:+1: Need this PR

**Comment by Benau** [comment]
Maybe you can share the same code with ctf team drawing....

**Comment by Benau** [comment]
f47b410d92304008a675c12c69e944a58c80c86f

**Comment by luffah** [comment]
@benau

did you touch to the order of team display  ?? it is reversed : the current team shall be to bottom to be coherent with the map.

Not really satisfied with the font... there will be some ergonomic things to fix may white for the background.

Too, i'm sot sure the flags are useful while playing, but it is ok for me.

**Comment by Benau** [comment]
We need a uniform ui for all game modes, also your choice of font cannot display unicode player name

There is no such thing as a fixed team side especially for addons soccer

**Comment by Benau** [comment]
You can check if minimap is inverted in track and decide to put which side first (only work with minimap looks like icy)

**Comment by luffah** [comment]
> You can check if minimap is inverted in track and decide to put which side first (only work with minimap looks like icy)

All minimaps in soccer mode don't looks like icy ?

**Comment by Benau** [comment]
like addon vivid vacuum

**Comment by luffah** [comment]
Not sure vivid vacuum is a good example, it is a recent and buggy map. (player is drawn outside of the minimap). 
If you mention the case of a minimap that can be horizontal (not everytime the best choice...), there is many common ergonomic principle that sadly depends on the reading direction (top to bottom, left to right - the eye start at left point of the minimap).

IMO, the eyes will seek a normalized order team order in list and minimap. 
Therefore, a specific minimap direction shall be put in the Human Interface Guide and there shall be more restrictive rules on making maps to respect the UI parts.

**Comment by Benau** [comment]
Lol penny and crystal will be unhappy

**Comment by Benau** [comment]
Lol bike must use iPhone!

**Comment by Benau** [comment]
Anyway do u want to fix that (just for icy) or I should do that for you?

**Comment by luffah** [comment]
As you think it shall be done. You may have other things to do. But i will not do it today because i have other things to do too...

**Comment by Benau** [comment]
20bcd1ae05baba477eba7bae2fc9f5f6dfb1d311

**Pull request closed without merging**
