### PR TITLE
Add new GPwin cutscene

### PR DESCRIPTION
**Pull request by qwertychouskie**
This is V1, I might make a modified version soon.
[winGP-new.zip](https://github.com/supertuxkart/stk-code/files/1116605/winGP-new.zip)

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Video (I made some small tweaks since then): https://jacobspctuneup.tk/gpwin.webm

**Comment by qwertychouskie** [comment]
Version with trimmed blend:
[winGP-new.zip](https://github.com/supertuxkart/stk-code/files/1116697/winGP-new.zip)

**Comment by qwertychouskie** [comment]
More throughly trimmed version:
[winGP-new.zip](https://github.com/supertuxkart/stk-code/files/1117449/winGP-new.zip)

**Comment by auriamg** [comment]
It's still got tons of seemiengly uncessary textures such as "splatting_test.png" and others, and a huge plane that doesn't need to be that big for such a small scene. Please take your time to provide a clean blend made specifically for that scene, and not "quick hacks".

**Comment by qwertychouskie** [comment]
Fully trimmed version:
[winGP-new-trimmed.zip](https://github.com/supertuxkart/stk-code/files/1126318/winGP-new-trimmed.zip)

**Comment by auriamg** [comment]
In the new version, there no longer appear to be cheering people and cheering monkeys? Where are they?

There also are errors logged on the terminal which should be fixed

```
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_top.png.
[error  ] track: Sky-box texture 'skybox_top.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_bottom.png.
[error  ] track: Sky-box texture 'skybox_bottom.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box texture 'skybox_side.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box texture 'skybox_side.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box texture 'skybox_side.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box texture 'skybox_side.png' not found - ignored.
[error  ] track: A skybox needs 6 textures, but 0 are specified
[error  ] track: in '../data/../../stk-assets/tracks/gpwin/scene.xml'.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load lightbox_top.png.
[error  ] track: Sky-box spherical harmonics texture 'lightbox_top.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_bottom.png.
[error  ] track: Sky-box spherical harmonics texture 'skybox_bottom.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box spherical harmonics texture 'skybox_side.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box spherical harmonics texture 'skybox_side.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box spherical harmonics texture 'skybox_side.png' not found - ignored.
[error  ] STKTexManager: While loading track '../data/../../stk-assets/tracks/gpwin/track.xml'
[error  ] STKTexManager: Failed to load skybox_side.png.
[error  ] track: Sky-box spherical harmonics texture 'skybox_side.png' not found - ignored.
```

**Comment by qwertychouskie** [comment]
Did you copy the textures to the exported folder?  About the scenery, maybe you have "Geometry Detail" turned down?

**Comment by auriamg** [comment]
THanks, merged

**Pull request merged**
