### PR TITLE
Fix AngelScript build on FreeBSD non-x86

### PR DESCRIPTION
**Pull request by myfreeweb**

### CODE REVIEW

**Comment by Benau** [comment]
Do you think you can sumbit it to upstream angelscript also?

**Comment by myfreeweb** [comment]
I don't see a pull request type thing, but the website mentions emailing the author with suggestions. Doing that now :)

**Comment by myfreeweb** [comment]
update: this will be included upstream.

**Comment by Benau** [comment]
good and merged

**Pull request merged**
