### PR TITLE
haiku elevate the thread priority from B_DISPLAY_PRIORITY to B_URGENT…

### PR DESCRIPTION
**Pull request by devnexen**
…_DISPLAY_PRIORITY attempt

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by devnexen** [comment]
@panos

**Comment by panos** [comment]
Wouldn't setting `B_REAL_TIME_DISPLAY_PRIORITY` be more correct?

**Comment by devnexen** [comment]
isn t it more for tasks like audio processing ?

**Comment by devnexen** [comment]
see no real difference in my side but I do not run haiku on real hardware tough.

**Comment by panos** [comment]
[The Be Book](https://www.haiku-os.org/legacy-docs/bebook/BLooper.html) says that it should be used, but *only* the threads that get involved with rendering, which is also something that Adrien also brought up before. Not 100% sure about this.

**Comment by Benau** [comment]
changing texture thread is useless because it's only for loading texture 

tbh i'm not in favour of premature optimization

**Comment by devnexen** [comment]
I also think it changes nothing regardless, the default priority is ok as is.

**Comment by panos** [comment]
> I also think it changes nothing regardless, the default priority is ok as is.

Thing is, how does the system react under heavy load?

**Comment by devnexen** [comment]
I think the best option is someone having haiku installed in real hardware developing it and assessing os reaction under heavy load.

**Pull request closed without merging**
