### PR TITLE
UI fix bundle XIII

### PR DESCRIPTION
**Pull request by dumaosen**
## Agreement
```
By creating a pull request in stk-code, you hearby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
why do u need to change src/states_screens/grand_prix_win.cpp?

**Comment by dumaosen** [comment]
because the texts are badly placed in high resolution

**Comment by qwertychouskie** [comment]
It looks like you moved the item icons to the icons folder, nice!  Been wanting that for a bit :)  If you could also adjust the race GUI code to use these icons, so that the icon theme can change these icons, that would be awesome :)

**Comment by dumaosen** [comment]
No it's not Qwerty. In my opinion race GUI should be apart from the other GUI. We can change the icons in the help menu in order to make it fit to the skin, but it won't fit the style of the in-game GUI if it can also influence the in-game powerup icons.

**Comment by Benau** [comment]
i dont want to duplicate power icons png in both models and data/gui/icons, especially now they are the same

**Pull request merged**
