### PR TITLE
Include linux/sysctl.h rather than sys/sysctl.h on non-glibc systems

### LINKED ISSUE #4172: Alpine Linux sysctl.h build failure
I'm trying to package SuperTuxKart for Alpine Linux. This distribution uses Musl rather than glibc and this seems to cause an issue.

When compiling Irrlicht I get the following:

```
/home/builder/aports/testing/supertuxkart/src/stk-code-1.0/lib/irrlicht/source/Irrlicht/COSOperator.cpp:20:10: fatal error: sys/sysctl.h: No such file or directory
   20 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
```

Looking at [the source](https://github.com/supertuxkart/stk-code/blob/master/lib/irrlicht/source/Irrlicht/COSOperator.cpp#L17), it includes `<sys/sysctl.h>` unless the platform is Android. However, at least on Alpine Linux (and I guess this is due to using Musl), it should be `<linux/sysctl.h>` instead, just as on Android.

The following snippet fixes the issue.
```
diff --git a/lib/irrlicht/source/Irrlicht/COSOperator.cpp b/lib/irrlicht/source/Irrlicht/COSOperator.cpp
index ba9612fc9..70d6193af 100644
--- a/lib/irrlicht/source/Irrlicht/COSOperator.cpp
+++ b/lib/irrlicht/source/Irrlicht/COSOperator.cpp
@@ -14,7 +14,7 @@
 #if !defined(_IRR_SOLARIS_PLATFORM_) && !defined(__CYGWIN__)
 #include <sys/param.h>
 #include <sys/types.h>
-#ifdef ANDROID
+#if defined(ANDROID) || !defined(__GLIBC__)
 #include <linux/sysctl.h>
 #else
 #include <sys/sysctl.h>
```

I would PR this, but it seems Irrlicht gets auto-copied and modified using some script so I'm not sure what to do here.

### PR DESCRIPTION
**Pull request by PureTryOut**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
I'm not sure if SuperTuxKart is supported on non-Linux and macOS *nix platforms like BSD, as this might break it.

Anyways, this fixes #4172.

### CODE REVIEW

**Comment by Benau** [comment]
```
/Users/travis/build/supertuxkart/stk-code/lib/irrlicht/source/Irrlicht/COSOperator.cpp:18:10: fatal error: 'linux/sysctl.h' file not found
#include <linux/sysctl.h>
```
On OSX travis 

maybe there is some define for musl only?

**Comment by PureTryOut** [comment]
There isn't sadly. Then again, it shouldn't have to mark itself as different. Code that works on Musl should also just work on say uclibc or any other POSIX compatible C std.

Maybe we can do the check other way around then? Like `if unix and macOS then <do stuff> else if unix and glibc then <do stuff> else <do android and non-glibc stuff>`?

**Comment by Benau** [comment]
check using cmake script?

**Comment by PureTryOut** [comment]
I pushed a new change, now checking if the platform is Linux and `__GLIBC__` _hasn't_ been set. Hopefully should work better?

That said, it seems glibc is deprecating `<sys/sysctl.h>` and in case of Linux `<linux/sysctl.h>` should be used anyway? Source https://github.com/dotnet/coreclr/pull/27048

**Pull request merged**
