### PR TITLE
Specify bash

### PR DESCRIPTION
**Pull request by licaon-kter**
Fix https://github.com/supertuxkart/stk-code/issues/4408

### CODE REVIEW

**Comment by Benau** [comment]
no mpl agreement.....

If deve thinks this is a correct fix then just change himself....

Btw I seem to remember you said some bash function in make.sh is not portable

**Comment by licaon-kter** [comment]
> no mpl agreement.....

Yeah, whatever

> If deve thinks this is a correct fix then just change himself....

So why are PRs open for this repo then? Strange answer

> Btw I seem to remember you said some bash function in make.sh is not portable

I did not say _that_

**Comment by Benau** [comment]
.....those questions are for @deveee ...

Wait few days for him....

**Comment by Benau** [comment]
deve is busy  duda at the moment lol

**Comment by deveee** [comment]
I changed the bash-specific functions, so #!/bin/bash is not needed now
https://github.com/supertuxkart/stk-code/commit/801675603cca43cc174fe7587099663bbbbb6ace

And if you need some modifications for fdroid we can add eg. FDROID_BUILD variable there and then if [ $FDROID_BUILD -eq 0 ] to skip some code.

Or for system gradle
```
diff --git a/android/make.sh b/android/make.sh
index 36c5d3842..dbb008e64 100755
--- a/android/make.sh
+++ b/android/make.sh
@@ -708,21 +708,27 @@ if [ -f "/usr/lib/jvm/java-8-openjdk-amd64/bin/java" ]; then
     export PATH=$JAVA_HOME/bin:$PATH
 fi
 
+export GRADLE_EXEC="./gradlew"
+
+if [ ! -z "$USE_SYSTEM_GRADLE ]; then
+    GRADLE_EXEC="gradle"
+fi
+
 export ANDROID_HOME="$SDK_PATH"
-./gradlew -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
-          -Pbuild_tools_ver="$BUILD_TOOLS_VER"       \
-          -Pstorepass="$STK_STOREPASS"               \
-          -Pkeystore="$STK_KEYSTORE"                 \
-          -Palias="$STK_ALIAS"                       \
-          $GRADLE_BUILD_TYPE
+$GRADLE_EXEC -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
+             -Pbuild_tools_ver="$BUILD_TOOLS_VER"       \
+             -Pstorepass="$STK_STOREPASS"               \
+             -Pkeystore="$STK_KEYSTORE"                 \
+             -Palias="$STK_ALIAS"                       \
+             $GRADLE_BUILD_TYPE
 
 if [ "$GRADLE_BUILD_TYPE" = "assembleRelease" ]; then
-./gradlew -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
-          -Pbuild_tools_ver="$BUILD_TOOLS_VER"       \
-          -Pstorepass="$STK_STOREPASS"               \
-          -Pkeystore="$STK_KEYSTORE"                 \
-          -Palias="$STK_ALIAS"                       \
-          "bundleRelease"
+$GRADLE_EXEC -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
+             -Pbuild_tools_ver="$BUILD_TOOLS_VER"       \
+             -Pstorepass="$STK_STOREPASS"               \
+             -Pkeystore="$STK_KEYSTORE"                 \
+             -Palias="$STK_ALIAS"                       \
+             "bundleRelease"
 fi
 
 check_error
```
so that you can define USE_SYSTEM_GRADLE in fdroid build script.

**Comment by licaon-kter** [comment]
> I changed the bash-specific functions, so #!/bin/bash is not needed now

I've already pushed a new recipe that avoids these issues, I'll retest with the new changes asap.

> And if you need some modifications for fdroid we can add eg. FDROID_BUILD variable there and then if [ $FDROID_BUILD -eq 0 ] to skip some code.

I don't feel like adding more cases helps, if the changes are just some `sed`'s.

The new build block: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.supertuxkart.stk.yml#L166-235

**Pull request closed without merging**
