### PR TITLE
Allow crash dialog for MinGW build

### PR DESCRIPTION
**Pull request by qwertychouskie**

### CODE REVIEW

**Comment by qwertychouskie** [comment]
capture

This was on a RelWithDebInfo cross-compiled MinGW 64-bit test build.  `cv2pdb -C  supertuxkart.exe` was used to make the PDB.

**Comment by qwertychouskie** [comment]
The only sorta-problem I had was that it took about a minute after STK freezing for the crash dialog to pop up.

**Comment by qwertychouskie** [comment]
Any thoughts on this?  The main STK builds need to be switched to MinGW builds because of https://github.com/supertuxkart/stk-code/issues/3344, and it would be nice to still have crash dialogs.

**Comment by qwertychouskie** [comment]
Here's a test build: https://jacobspctuneup.tk/STK/stk-code-mingw-crash-handling.zip

In this build LinkHelper::openURL is rigged to crash, the donate button in the credits works for triggering it.

@deveee You have a MinGW setup, right?  Any thoughts on this PR?

**Comment by deveee** [comment]
I wonder if handler for memory allocation error should be totally disabled. Because in this case we should free some memory and not alloc more to display window with crash report. Especially that if there are some memory leaks or not enough ram, then it will probably crash in random place anyway. And I'm not sure if VS function is smart enough, so that it will throw exception.

There is std::set_new_handler() that works with mingw, but they explicitly say that you must free some resources or abort app.

And if everything else works, then I will merge this evening.

**Comment by deveee** [comment]
Tbh. I'm not convinced... Because mingw is typically used for self-compilation. And you need additional external tools like cv2pdb to create pdb file. So that most people will just get wrong crash reports.

**Comment by qwertychouskie** [comment]
The reason for this is https://github.com/supertuxkart/stk-code/issues/3344#issuecomment-455364398.  Basically for the official Windows builds we either have to switch to MinGW builds or direct users to MS's website to download MSVCRT (which would be very bad UX).  Or maybe it's possible to hex edit the MSVC-compiled binary to point to the unversioned MSVCRT dll?

**Comment by qwertychouskie** [comment]
I just force-pushed to remove a small string change that was unneeded, since STK is now in string freeze.  Since 0.10 may be built with MinGW (https://github.com/supertuxkart/stk-code/issues/3344#issuecomment-476488642), it would be good to have this merged.

Also, the diff shows some lines as "changed" that aren't, not sure why. (line ending weirdness?)  Anyways, it won't harm anything.

**Comment by Benau** [comment]
i don't feel like merging pr with fixme

**Comment by Benau** [comment]
The slowness probably because the pdb file generated is not as good as msvc

So we either keep current way or use mingw build with accepting the slowness

**Comment by deveee** [comment]
For mingw you don't need pdb files. You should be able to do the same as on linux - build with debug symbols, strip symbols for the release package, and then addr2line to decode the backtrace.

**Comment by qwertychouskie** [comment]
Closing this PR as it is obsoleted by https://github.com/supertuxkart/stk-code/commit/c710057db1efd7f71f4f8de52368234f8ef25890.

**Pull request closed without merging**
