### PR TITLE
Fixing selection issue on end-race screen

### PR DESCRIPTION
**Pull request by Fantasmos**
Here's the fix for gamepad controllers. May be worth making this part of the setvisible function.

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Yeah, it would probably make sense to make `setFocusable()` part of `setVisible()`.

**Comment by auriamg** [comment]
Sorry for the late feedback - this seems like a good fix, though as discussed on IRC it may make sense to make this behavior automatic for hidden items.

Also, you handled one specific buttons, but other buttons may be shown or hidden even on that one specific screen, it would make sense to support all of them

**Comment by Fantasmos** [comment]
@auriamg I've had a go at making it a global fix, however it doesn't look like simple. I tried editing the code that checks if a button is focusable, but didn't seem to fix it (however I was rushing a bit when doing it). I'll have another go in a few days hopefully.

**Comment by auriamg** [comment]
Okay, I've merged the workaround, a more complete fix can always come later, thanks

**Pull request merged**
