### PR TITLE
Purpel.stkskin

### PR DESCRIPTION
**Pull request by qaugustijn**

### CODE REVIEW

**Comment by Benau** [comment]
First, u miss purpel skin data (png file), also no font color define in your stkskin, which is required for next stk version

**Comment by qaugustijn** [comment]
How to upload a png file to this repository of Github?

**Comment by Benau** [comment]
U cannot file to github, u need a local copy of your fork.

Than you can push

Also it would be good if your new skin is drawn from scratch, so some skin(ruby?) can be replaced, which it's gimp-color

**Comment by qaugustijn** [comment]
I have created a folder with the png files of the new skin and I have tested in supertuxkart.

**Comment by Benau** [comment]
You should test with current (git) version of supertuxkart for future compatibility.

**Comment by deveee** [comment]
This pull request doesn't contain "purpel" directory, which as I see you use in your skin. Please, prepare proper pull-request with all needed files, so that it could be useful for others.

If you think that your skin is really nice, and you don't know how to prepare pull-request, then just upload it somewhere as a zip file.

**Pull request closed without merging**
