### PR TITLE
More angelscript fixes

### PR DESCRIPTION
**Pull request by Vincent-C**
This is a followup for PR #2195; the earlier PR contributed by @jcowgill fixes build failures on most archs mentioned in the initial bug report in #2194 except for armel. This PR fixes the armel build on Debian as well (build logs can be found [here](https://buildd.debian.org/status/package.php?p=supertuxkart&suite=unstable)). Thanks for considering!

### CODE REVIEW

**Comment by jcowgill** [comment]
Sorry about my ARMv4 patch not working.

It looks like you actually fixed the assembly to work on ARMv4 so do you need my second patch at all? Also the commit message is wrong because you ported it to ARMv4 and haven't actually disabled anything :)

**Comment by Vincent-C** [comment]
No worries! Thanks for all the work you've put in to make STK compile on the other archs that were failing.

I actually haven't tested a build without your second patch yet (it took forever to finish a single build on the Debian armel porterbox I was using), but it doesn't hurt to include it. Agreed about the silly commit message though, not sure what I was thinking. :)

**Comment by auriamg** [comment]
The main issue with these pull requests is that while we integrate the angelscript sourcecode into STK for convenience, we haven't actually forked angelscript nor do we intend do. So modifications to angelscript itself should be probably submitted upstream, unless there's some bits specific to the STK build system of course

**Comment by Vincent-C** [comment]
Ack, I've already submitted a patch upstream (via email to the upstream author); I just wasn't sure earlier whether or not the embedded angelscript copy in STK was intended as a convenience copy or a fork. I can just keep this as a Debian-specific patch for now. Thanks anyways!

**Comment by hiker** [comment]
If the patch is useful and was submitted upstream, I think we can include it?

**Comment by Vincent-C** [comment]
Just FYI, the patch was applied upstream as svn r2177.

**Comment by auriamg** [comment]
Thanks! We will eventually upgrade to a newer version of angelscript and then we'll get this fix. Given that STK doesn't currently support ARM I'd say there is no urgent need to ugprade to a newer AS

**Comment by auriamg** [comment]
We have just updated to a newer version of angelscript, that should hopefully address those issues. Please reopene if there are more issues

**Pull request closed without merging**
