### PR TITLE
fix #4123

### LINKED ISSUE #4123: Story Mode Timer is not set to zero for a new account after previous player
## Description
When there are several offline accounts for a speedrun, switching between them and quitting/launching can make the timer value invalid.

### First way

Create an offline account A and start the story mode from it, wait for some time (e.g. 30 seconds). Then exit to the main menu and create a new offline account B, then quit the app. When you relaunch, try to start the story mode from B, the timer will show time starting from nonzero value (specifically, the time you waited with A).

### Second way

Create new offline accounts A and B and start the story mode from A, wait for some time. Then exit to the main menu and try to launch story mode for B, the timer will display 99:59:99 and will not change.

Also if the timer is not enabled from the settings before the run starts, you probably can see no fractional parts of a second (.561).

## Configuration

STK release version: git updated on Nov 1, 2019, commit 770d02b

STK Source (PPA, distribution package, official binary, etc.): compiled from source

System: Ubuntu 19.04

Graphics card: 

CPU: 

Gamepads/keyboards models if related to the issue: 

## Additional information

stdout.log:
```

```

input.xml:
```xml

```

Error message:
```

```

### PR DESCRIPTION
**Pull request by GuillaumeBft**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
We put { in the next line, also space after if

**Comment by GuillaumeBft** [comment]
Sorry, I won't forget for the next one

**Comment by Benau** [comment]
@kimden can you see if your bug is fixed after this patch?

**Comment by kimden** [comment]
Yes, it's fixed. The only thing that remains is the last paragraph of my issue (about milliseconds), but I guess I should have made a separate issue for that since it's more related to having two timers.

**Pull request merged**
