### PR TITLE
Allow to use system angelscript

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by auriamg** [comment]
Hi,
could you explain why you modified the array part?

**Comment by ignatenkobrain** [comment]
@auriamg because GitParamTypeId is deprecated. I didn't know about scripting branch. Can you merge this to scripting branch?

**Comment by auriamg** [comment]
Unfortunately the branch is not quite finished yet, but it should be mergeable soonish. Meanwhile I cannot merge your PR though since it would break trunk compilation

**Comment by auriamg** [comment]
The scripting branch and been merged, and your pull request too, thanks

**Pull request merged**
