### PR TITLE
Add gamerzilla support to achievements.

### PR DESCRIPTION
**Pull request by dulsi**
This allows achievements to be shared on Hubzilla sites using the Gamerzilla plugin. There is also support for GameHub to display achievements. That is still waiting to be merged into the official GameHub repository.
[Screenshot of Gamerzilla](https://social.freegamedev.net/photo/84b6569c-da54-4506-88fa-7c76d869e89e-2.png)

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by qwertychouskie** [comment]
`achievement0.png`/`achievement1.png` seem pixelated, maybe re-export from the SVG at the exact needed resolution?

**Comment by Benau** [comment]
hmm you should use the default icon (not the "cartoon" skin)....

**Comment by Benau** [comment]
...lol seems that your project is very new compared to the rest existing project...

**Comment by dulsi** [comment]
qwertychouskie: That is how they export at 64x64 pixels.

Benau: qwerty suggested the modern svg files. Is there an svg for the default icons or should I just resize the png files? Since they are 128x128, it probably won't matter much if I resize the png.

**Comment by Benau** [comment]
hmm no svg icon exists for gp_new.png... you can just resize the png

if your project is not widely adopted then it may not be a good candidate to bundle.... (or alayan!)

**Comment by Alayan-stk-2** [comment]
What's good : 
- You're providing the code to support it yourself, this is appreciated
- Some users might like having achievements shared on a platform meant to handle multiple games.

What's bad : 
- I couldn't find info on Gamerzilla through a casual search, the project seems very obscure for now. You have to start somewhere I guess.
- The PR sprinkles ifdefed gamerzilla code in multiple files. This makes future maintainability more complicated.
- When the list of achievements is overhauled and some specific achievement code will be changed (this should happen for 2.0), this will not work out of the box. By having this in our codebase, it puts the burden on us to keep it working.
- It reuses STK's names and descriptions for achievements, but loses translations in the process.

**Comment by qwertychouskie** [comment]
Here's a 64x64 copy:
achievement_round
And grayscale:
achievement_round_grayscale

**Comment by dulsi** [comment]
Alayan: I moved all the Gamerzilla code to the WebAchievementStatus class. If you wanted to support Steam or another achievement system you would just need to modify that.

To eliminate the duplicate achievement list, I should be able to dynamically build it from the stk achievement list.

Translations are not currently support by Gamerzilla. I don't plan on adding it at the moment. If I do add it, I should be able to use your translations when dynamically building the achievement information.

I'm working on making it more popular but that isn't a quick thing to fix. :) Assuming I get the duplicate achievement list issue resolved, do you think it could be merged?

**Comment by dulsi** [comment]
Achievement list is now generated from supertuxkart's list instead of using another file. The only additional work for supertuxkart team would be to update the "version" in that achievements.xml when the achievements change.

Images are updated.

**Comment by Alayan-stk-2** [comment]
I haven't closely review the code, but this looks much better. It addresses my most significant concerns.

Assuming the low-level details of the code are ok, I'd be fine with a merge.

**Comment by Benau** [comment]
so pr is ready now?

**Comment by Benau** [comment]
one suggestion to make your system more popular is to avoid using lgpl license...

**Comment by dulsi** [comment]
I will probably be updating the license to a more permissive one in the next release. I looked at SDL and found they had a more permissive one so it makes sense to do the same. Any word on merging this?

**Comment by Benau** [comment]
ok

**Pull request merged**
