### PR TITLE
Add left and right side camera views on kart controls

### PR DESCRIPTION
**Pull request by luffah**
Add left and right side camera views on kart controls :
- add 2 keys for keyboard  to look at left and at right
- add 1 button on gamepad to look at left (imcomplete choice, to discuss)
- no influence (currently) on shooting items 

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by Benau** [comment]
You can keep only the camera mode changes only and use some F1-12 key to control camera object instead, see debug.cpp

**Comment by luffah** [comment]
I freeze of some days, maybe 2 weeks.

I intend to change the code, agreeing to :
- this experimental (new) feature shall not be usable without modifying the user config file
- network logic shall not be impacted

Given, i can't align change with artist_debug_mode because of existing keys and features that are too much for a simple camera addition, I'll look to put that as a new hidden option in user config.

Too if the keys can't be set, this PR is useless.
Therefore i'll propose keybinds only if the hidden option is on.

**Comment by Benau** [comment]
i'm not even sure we want this feature... (android user can't do the same)

**Comment by Benau** [comment]
Or maybe just use higher fov for arena (soccer included) modes? (like 100, try change in stk_config)

I assume your pr purpose is only that?

**Comment by luffah** [comment]
> I assume your pr purpose is only that (better soccer gameplay!)!?
yes, it is for semi-hardcore gamers :
- in soccer mode, it allows the goalkeeper to follow the ball in any position
- in arena mode, it allows to check every body around, and have a better hide and seek strategy
- in race mode, it allows to see very tight turn and help to find shortcuts

**Comment by Benau** [comment]
Lol you cannot even drive sideway for gatekeeper

**Comment by luffah** [comment]
> Lol you cannot even drive sideway for gatekeeper

Oh good idea... not a camera change but add the possibility to drive sideway like a space ship :p

**Comment by luffah** [comment]
I didn't found a minimal way that allow to add the keys without adding m_look_left and m_look_right in kart_control.hpp . It seems to be required to (given the camera shall go back to normal when the key is released - in kart.cpp)  keep the view active while the key is pressed (in local_player_controller.cpp).

**Comment by luffah** [comment]
Tested for some hours. Finally, this change is more aesthetical. I'm not satisfied :(

**Comment by luffah** [comment]
New path to the feature : https://github.com/luffah/stk-code/tree/side-camera-normal

**Pull request closed without merging**
