### PR TITLE
Add new speedfore and 2 new skins

### PR DESCRIPTION
**Pull request by qaugustijn**
I have create a new speedfore and 2 new skins:
stk-code / data / gui / speedfore.png
stk-code / data / gui / skins / Green.stkskin
stk-code / data / gui / skins / green / *
stk-code / data / gui / skins / Purpel.stkskin
stk-code / data / gui / skins / purpel / *

### CODE REVIEW

**Comment by Benau** [comment]
Your green is almost the same as the forest skin,  and ocean and ruby skin should provide similar feelings to purpel.

Sorry for your work to be duplicated, but i don't find a good way to integrate them with current stk...........

**Comment by qaugustijn** [comment]
I have maked more skins with this colors:

- Orange (looks like Peach)
- Red
- Yellow
- Blue (looks like Ocean)

Which is good for the new version of stk?

**Comment by Benau** [comment]
![meme]
(http://cdn.meme.am/instances2/500x/3483427.jpg)

**Comment by auriamg** [comment]
Not bad, but in general we favor quality of quantity - a brand new high-quality skin would be a lot more interesting than a lot of minor variations on the current ones. I guess we will need to have a team discussion on this, please allow a little time as some team members are unavailable during the holidays

**Comment by qaugustijn** [comment]
These are skin similar to existing skins:
- Green (looks like forest, this skin isn't necessary)
- Orange (looks like peach, this skin isn't necessary)
- Blue (looks like ocean, this skin isn't necessary)

Are these skins interesting for SuperTuxKart?
- Red (a new name for this skin can be named 'Fire')
- Yellow (is there a good new name for this skin? something like 'Banana')
- Purple (is there a good new name for this skin?)

**Comment by auriamg** [comment]
Sorry about that, but in general as I was saying we would be more interesting in completely new UI designs, not just recolors of the current ones. We already have 4 colors, I see little use in adding more colors. Red would look too agressive perhaps, yellow doesn't offer good contrast

So this leaves us with purple, which could work. However in this PR you named it "purpel", should be "purple". Maybe you can open another PR with only the purple skin, written correctly?

(also that should probably be the last recoloring of the current skin, we'll have quite enough colors like that!)

**Pull request closed without merging**
