### PR TITLE
Reduce number of places version number needs to be changed on release

### PR DESCRIPTION
**Pull request by qwertychouskie**
Just greasing the wheels of the releasing process a little bit. :)  ~Note that std::regex_replace is cpp11~ (no longer needed).

### CODE REVIEW

**Comment by deveee** [comment]
Just note that I'm ok with upgrade to gcc 4.9.

STK 0.9.4 linux package probably will be based on Debian Jessie (gcc 4.9.2) or Ubuntu 16.04 (gcc 5.3.1). Or maybe I will compile whole package using Android script and dependencies.

For Android I prefer gcc <= 4.9.2, but in worst case I can hack android script to make it working with clang.

**Comment by leyyin** [comment]
An alternative would be just to use a `std::string` replace.

Add this to the `namespace StringUtils` (see `string_utils.hpp`).
```cpp
std::string findAndReplace(const std::string& source, const std::string& find, const std::string& replace)
{
    std::string destination = source;
    std::string::size_type found_position = 0;

    // Replace until we can't find anymore the find string
    while ((found_position = destination.find(find, found_position)) != std::string::npos)
    {
        destination.replace(found_position, find.length(), replace);
        // Advanced pass the replaced string
        found_position += replace.length();
    }
    
    return destination;
}
```

And use it like this:
```cpp
// To be honest I would use something else than "STKVERSION" to be the key to search
// "$STKVERSION$" or maybe "__STKVERSION__"
line = StringUtils::findAndReplace(line, "$STKVERSION$", STK_VERSION);
```

**Comment by hiker** [comment]
+2 for everything @leyyin just wrote :)

**Comment by qwertychouskie** [comment]
I just tested @leyyin's code and it seems to work, so I force-pushed the commit (removing the Travis-changing commit).  My idea was to make things easier (especially if a "0.9.3.1" is released to fix the add-ons manager crash with Russan and the gamepad crash with gamepads that report too many buttons), not more complicated. :)

**Comment by auriamg** [comment]
@hiker I'd tend to merge this, agreed?

**Comment by qwertychouskie** [comment]
Thanks!

**Pull request merged**
