### PR TITLE
Add multilingual logo support

### PR DESCRIPTION
**Pull request by CodingJellyfish**
## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```
For #4074
Riso upload your Chinese logo! Also a Japanese and Korean one is good.

### CODE REVIEW

**Comment by Benau** [comment]
korean can not be in artistic......

**Comment by risostk** [comment]
maosen, created a PR in NeoSTK.

**Comment by dumaosen** [comment]
Update translation source after merge please!

**Comment by Benau** [comment]
riso / maosen if you think zh_CN (or maybe jp_JP too) stk logo has improvement for localization i would rather add a special code handling instead of messing up the translation class

maybe jerry can tell too

**Comment by Benau** [comment]
add a data/gui/logo.png into translation string will confuse translators very much (and it's not really a correct english, unless the rest)

**Comment by Benau** [comment]
outdated with conflicts... 

maybe benau can do that for you (without too much hack) when CCP is taken down by president donald j trump (soon!)

**Pull request closed without merging**
