### PR TITLE
Support disabling race intro sound

### PR DESCRIPTION
**Pull request by antoniusriha**
I've added a user config entry for disabling the sound at race start. This is useful when you're listening to some music on your PC and don't want it to clash acoustically with the race start sounds.

### CODE REVIEW

**Comment by auriamg** [comment]
Hi,

this is not a bad idea but I'm really not sure adding a new flag is necessary. I think it may be better to just force these sounds off if music is disabled, since they are kind of like music? That would avoid the creation of yet another flag. That is kind of a hack but is much simpler

**Comment by antoniusriha** [comment]
I personally wouldn't have a problem with disabling the race start sounds with the music flag. Some people though might need the acoustic cue to time the race start better. This is why I added a new flag.

**Comment by auriamg** [comment]
I was only referring to the little "get ready" music that plays _before _"ready-set-go". The little chimes that play on ready-set-go are definitely sound effects and should stay there

**Comment by antoniusriha** [comment]
I've removed the new additional flag. Race intro sound is now controlled by the music_on flag. Ready-set-go sounds are always on.

**Comment by Benau** [comment]
Minor problem:
If no m_track_intro_sound is played, the race will start faster (ie thunderbird will appear immediately)

**Comment by antoniusriha** [comment]
I have fixed the timing issue by adding a delay. This resulted in an awkward silence at the beginning of the race, so I decided to make the kart engines start earlier, if the intro music is off.

**Comment by auriamg** [comment]
Seems good, thanks. I'm not sure I like having a special case for the engines, but I don't have anything better to suggest so that will have to do

**Pull request merged**
