### PR TITLE
Possible to turn volume all the way down

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by Benau** [comment]
the min_value 0 is a quick hack for just for you (private use), the proper fix is to detect whether this widget is zero, and then SFXManager::get()->toggleSound(false) or music_manager->stopMusic().

**Comment by qwertychouskie** [comment]
Isn't this what the "Enabled" checkbox right above the volume control for?

**Comment by auriamg** [comment]
The enabled checkbox definitely needs to be considered here - if we allow the sound to go to 0 then the code will need to detect it and actually turn the feature off completely, that would be preferable

**Comment by qwertychouskie** [comment]
I think due to the "Enabled" toggle right above the volume level control, (and a lack of activity on this PR,) this should be closed.

**Comment by scootergrisen** [comment]
Why not fix the problem instead?

**Comment by nado** [comment]
Because you’re the only one to see a problem here ?

**Comment by scootergrisen** [comment]
Have you ever seen a volume control anywhere that is not made to turn the volume all the way down?

**Comment by auriamg** [comment]
Should we receive a PR that fully disables sound when it's turned down (i.e. really disables audio) then we could merge it. Meanwhile though, this is an extremely minor feature (you can get the same effect in one click) so I don't think anyone from the main team will be working on this

**Comment by qwertychouskie** [comment]
Should this be closed then?

**Comment by auriamg** [comment]
Yes, closing, this PR won't be merged as-is. If anyone wants to make another improved pull request, please create a new PR

**Pull request closed without merging**
