### PR TITLE
Sliders react to mouse

### PR DESCRIPTION
**Pull request by ZyperPL**
You can change slider/spinner's value by mouse click.
It works only on gauge spinners.

### CODE REVIEW

**Comment by auriamg** [comment]
Hi,

this is a step in the right direction, but I see a few things that could be improved

1) I don't quite get the following line. Unless there's something I missed, this division always yields 1 :

```
const float max_value = (float)(w->getMax() - w->getMin()) / (w->getMax() - w->getMin());
```

2) Placing the click handling code in the skin is very hackish, why not move the click handling code directly in onClick where it belongs?

**Comment by ZyperPL** [comment]
@auriamg 
Ok. I moved all the code to onClick() function of widget SpinnerWidget. 
But there's one thing that is wrong, I don't have m_left_border and image's height of SkinConfig::m_render_params. Is it possible to get those values from inside Widget class?

**Comment by auriamg** [comment]
Hi, that's a lot better, nice work! One last little think, hardcoding 110 and 128 is uneeded since you have access to coordinates in this way :

```
core::recti body_rect = m_children[1].getIrrlichtElement()->getAbsolutePosition();
```

This coordinate is not 100% perfect due to the skin adding some margins, but should suffice to work reasonbly well

**Comment by ZyperPL** [comment]
Thanks @auriamg 
I've changed that. Everything works, but now it's not pixel-perfect.
However I think user won't see the difference.

**Comment by auriamg** [comment]
Hi, thanks I've applied your pull request!
I made a few small changes, like remove unused code (Calculating x and y was never used) and also using roundf instead of adding +0.5

**Pull request merged**
